import 'dotenv/config';
import prisma from './config/db.js';

// const predefinedTags = [
//   // 🍔 RESTAURANTS & CAFES
//   { category: 'Restaurant', tag: 'Delicious Food', icon: '🍔' },
//   { category: 'Restaurant', tag: 'Great Atmosphere', icon: '✨' },
//   { category: 'Restaurant', tag: 'Fast Service', icon: '⚡' },
//   { category: 'Restaurant', tag: 'Friendly Staff', icon: '👋' },
//   { category: 'Restaurant', tag: 'Clean Space', icon: '🧼' },
//   { category: 'Restaurant', tag: 'Good Portions', icon: '🍲' },
//   { category: 'Restaurant', tag: 'Affordable', icon: '💰' },
//   { category: 'Restaurant', tag: 'Fresh Ingredients', icon: '🥗' },
//   { category: 'Restaurant', tag: 'Amazing Cocktails', icon: '🍸' },
//   { category: 'Restaurant', tag: 'Vegan Options', icon: '🌱' },
//   { category: 'Restaurant', tag: 'Cozy Vibe', icon: '☕' },
//   { category: 'Restaurant', tag: 'Family Friendly', icon: '👨‍👩‍👧‍👦' },

//   // 🏨 HOTELS & RESORTS
//   { category: 'Hotel', tag: 'Luxury Room', icon: '🏨' },
//   { category: 'Hotel', tag: 'Great Service', icon: '👔' },
//   { category: 'Hotel', tag: 'Super Clean', icon: '✨' },
//   { category: 'Hotel', tag: 'Comfortable Bed', icon: '🛏️' },
//   { category: 'Hotel', tag: 'Nice View', icon: '🌅' },
//   { category: 'Hotel', tag: 'Good Breakfast', icon: '🍳' },
//   { category: 'Hotel', tag: 'Quiet Room', icon: '🤫' },
//   { category: 'Hotel', tag: 'Great Location', icon: '🗺️' },
//   { category: 'Hotel', tag: 'Fast Wi-Fi', icon: '📶' },
//   { category: 'Hotel', tag: 'Beautiful Pool', icon: '🏊‍♂️' },
//   { category: 'Hotel', tag: 'Helpful Concierge', icon: '🛎️' },
//   { category: 'Hotel', tag: 'Pet Friendly', icon: '🐕' },

//   // 🛍️ RETAIL & SHOPPING
//   { category: 'Retail', tag: 'Great Selection', icon: '🛍️' },
//   { category: 'Retail', tag: 'Helpful Staff', icon: '🤝' },
//   { category: 'Retail', tag: 'Good Prices', icon: '🏷️' },
//   { category: 'Retail', tag: 'Clean Store', icon: '✨' },
//   { category: 'Retail', tag: 'Quality Products', icon: '⭐' },
//   { category: 'Retail', tag: 'Fast Checkout', icon: '⏱️' },
//   { category: 'Retail', tag: 'Trendy Styles', icon: '👕' },
//   { category: 'Retail', tag: 'Easy Returns', icon: '🔄' },
//   { category: 'Retail', tag: 'Friendly Cashier', icon: '😊' },
//   { category: 'Retail', tag: 'Well Organized', icon: '📦' },

//   // 🩺 MEDICAL & DENTAL
//   { category: 'Medical', tag: 'Caring Doctor', icon: '👨‍⚕️' },
//   { category: 'Medical', tag: 'Short Wait Time', icon: '⏱️' },
//   { category: 'Medical', tag: 'Clean Facility', icon: '🏥' },
//   { category: 'Medical', tag: 'Gentle Staff', icon: '💙' },
//   { category: 'Medical', tag: 'Clear Explanations', icon: '🗣️' },
//   { category: 'Medical', tag: 'Modern Equipment', icon: '🔬' },
//   { category: 'Medical', tag: 'Easy Scheduling', icon: '📅' },
//   { category: 'Medical', tag: 'Highly Professional', icon: '⚕️' },

//   // 💪 FITNESS & GYM
//   { category: 'Gym', tag: 'Great Equipment', icon: '🏋️' },
//   { category: 'Gym', tag: 'Clean Locker Rooms', icon: '🚿' },
//   { category: 'Gym', tag: 'Motivating Trainers', icon: '💪' },
//   { category: 'Gym', tag: 'Good Energy', icon: '⚡' },
//   { category: 'Gym', tag: 'Plenty of Space', icon: '🏃' },
//   { category: 'Gym', tag: 'Awesome Classes', icon: '🧘‍♀️' },
//   { category: 'Gym', tag: '24/7 Access', icon: '🕒' },
//   { category: 'Gym', tag: 'Friendly Vibe', icon: '🙌' },

//   // 💆‍♀️ SPA & SALON
//   { category: 'Spa', tag: 'Very Relaxing', icon: '💆‍♀️' },
//   { category: 'Spa', tag: 'Talented Stylist', icon: '✂️' },
//   { category: 'Spa', tag: 'Clean & Peaceful', icon: '🕊️' },
//   { category: 'Spa', tag: 'Great Massage', icon: '🧘' },
//   { category: 'Spa', tag: 'Beautiful Results', icon: '✨' },
//   { category: 'Spa', tag: 'Luxury Experience', icon: '💅' },

//   // 🚗 AUTOMOTIVE
//   { category: 'Automotive', tag: 'Honest Mechanic', icon: '🔧' },
//   { category: 'Automotive', tag: 'Fair Pricing', icon: '💵' },
//   { category: 'Automotive', tag: 'Fast Repair', icon: '⏱️' },
//   { category: 'Automotive', tag: 'Clear Communication', icon: '📱' },
//   { category: 'Automotive', tag: 'Quality Work', icon: '🚗' },
//   { category: 'Automotive', tag: 'Friendly Service', icon: '🤝' },

//   // 🏠 REAL ESTATE
//   { category: 'Real Estate', tag: 'Very Knowledgeable', icon: '🧠' },
//   { category: 'Real Estate', tag: 'Quick Responses', icon: '⚡' },
//   { category: 'Real Estate', tag: 'Smooth Process', icon: '📄' },
//   { category: 'Real Estate', tag: 'Found Dream Home', icon: '🏠' },
//   { category: 'Real Estate', tag: 'Great Negotiator', icon: '🤝' },
//   { category: 'Real Estate', tag: 'Highly Recommended', icon: '⭐' },

//   // ⭐ GENERAL / OTHER
//   { category: 'Other', tag: 'Excellent Service', icon: '⭐' },
//   { category: 'Other', tag: 'Highly Recommend', icon: '👍' },
//   { category: 'Other', tag: 'Very Professional', icon: '👔' },
//   { category: 'Other', tag: 'Great Experience', icon: '✨' },
//   { category: 'Other', tag: 'Friendly Team', icon: '🤝' },
//   { category: 'Other', tag: 'Quick Response', icon: '⚡' },
//   { category: 'Other', tag: 'Good Value', icon: '💰' },
//   { category: 'Other', tag: 'Reliable', icon: '🛡️' }
// ];

const predefinedTags = [
  {
    "food_and_dining": [
      { "icon": "🍲", "en": "Authentic Local Taste", "hi": "असली स्थानीय स्वाद", "pa": "पहाड़ा दा असली स्वाद" },
      { "icon": "🌶️", "en": "Perfect Spices", "hi": "बेहतरीन मसाले", "pa": "खरे मसाले" },
      { "icon": "🥬", "en": "Fresh Organic Veggies", "hi": "ताज़ा जैविक सब्ज़ियाँ", "pa": "ताजी क्यारी दी सब्जी" },
      { "icon": "🍱", "en": "Traditional Thali", "hi": "पारंपरिक थाली", "pa": "पुरानी रीति री थाली" },
      { "icon": "🔥", "en": "Hot & Fresh", "hi": "गरमा-गरम और ताज़ा", "pa": "ताता ते ताज़ा" },
      { "icon": "☕", "en": "Strong Ginger Tea", "hi": "कड़क अदरक वाली चाय", "pa": "कड़क अद्रक आली चाह" },
      { "icon": "🛖", "en": "Dhaba Style Vibe", "hi": "ढाबा स्टाइल माहौल", "pa": "ढाबे आला माहौल" },
      { "icon": "💸", "en": "Pocket Friendly", "hi": "किफ़ायती", "pa": "सस्ता ते खरा" },
      { "icon": "👨‍👩‍👧‍👦", "en": "Great for Families", "hi": "परिवार के लिए उत्तम", "pa": "टब्बर तांई बड्डा खरा" },
      { "icon": "🧹", "en": "Very Clean Kitchen", "hi": "साफ़-सुथरी रसोई", "pa": "सुथरा चौका" },
      { "icon": "⚡", "en": "Super Fast Delivery", "hi": "बहुत तेज़ डिलीवरी", "pa": "झटपट डिलीवरी" },
      { "icon": "🍰", "en": "Heavenly Desserts", "hi": "शानदार मीठा", "pa": "बड्डा स्वाद मीठा" },
      { "icon": "🥘", "en": "Rich Gravy", "hi": "गाढ़ी तरी", "pa": "गाढ़ी तरी" },
      { "icon": "🥤", "en": "Refreshing Drinks", "hi": "ताज़गी भरे पेय", "pa": "ठंडे ते ताजे शरबत" },
      { "icon": "🪑", "en": "Comfortable Seating", "hi": "आरामदायक बैठने की जगह", "pa": "बैठणे दी खरी जगह" },
      { "icon": "🌅", "en": "Amazing View", "hi": "सुंदर नज़ारा", "pa": "धौण को भालो नज़ारा" },
      { "icon": "🧂", "en": "Low Salt/Oil", "hi": "कम तेल-मसाला", "pa": "घट तेल-लूण" },
      { "icon": "🥗", "en": "Healthy Options", "hi": "सेहतमंद विकल्प", "pa": "सेहत तांई खरा खाणो" },
      { "icon": "🧤", "en": "Hygienic Handling", "hi": "साफ़-सफाई का ध्यान", "pa": "सफ़ाई दा पूरा ध्यान" },
      { "icon": "🐕", "en": "Pet Friendly", "hi": "पालतू जानवरों के अनुकूल", "pa": "पालतू जनावर तांई खरा" },
      { "icon": "🥟", "en": "Best Momos Ever", "hi": "सबसे बढ़िया मोमोज़", "pa": "सबन ते खरे मोमोज़" },
      { "icon": "🧇", "en": "Crispy Snacks", "hi": "कुरकुरे स्नैक्स", "pa": "करड़े ते करारे स्नैक्स" },
      { "icon": "🍳", "en": "Perfect Breakfast", "hi": "शानदार नाश्ता", "pa": "बड्डा खरा नाश्ता" },
      { "icon": "🌙", "en": "Late Night Cravings", "hi": "देर रात का खाना", "pa": "राती जो भूख मिटाणे तांई" },
      { "icon": "🥛", "en": "Fresh Lassi/Milk", "hi": "ताज़ा लस्सी-दूध", "pa": "ताजी लस्सी ते दूध" },
      { "icon": "🥯", "en": "Soft Breads", "hi": "नरम रोटियाँ", "pa": "नरम-नरम फुलके" },
      { "icon": "🍯", "en": "Local Honey Used", "hi": "स्थानीय शहद का उपयोग", "pa": "इथै दा शहद" },
      { "icon": "🌿", "en": "Vegan Friendly", "hi": "शुद्ध शाकाहारी", "pa": "शुद्ध शाकाहारी" },
      { "icon": "🍕", "en": "Cheesy Pizza", "hi": "चीज़ी पिज्जा", "pa": "चीज़ी पिज्जा" },
      { "icon": "🥪", "en": "Loaded Sandwiches", "hi": "भरपूर सैंडविच", "pa": "भरे रे सैंडविच" },
      { "icon": "🚗", "en": "Good Parking Space", "hi": "पार्किंग की अच्छी जगह", "pa": "गाड़ी तांई खुली जगह" },
      { "icon": "🎶", "en": "Live Music", "hi": "लाइव संगीत", "pa": "गाणे-बजाणे दा शौक" },
      { "icon": "🪔", "en": "Cozy Vibe", "hi": "प्यारा माहौल", "pa": "प्यारा जेहा माहौल" },
      { "icon": "🤝", "en": "Polite Servers", "hi": "विनम्र वेटर्स", "pa": "प्यारे वेटर्स" },
      { "icon": "📱", "en": "Free Wi-Fi", "hi": "मुफ्त वाई-फ़ाई", "pa": "फ्री इंटरनेट" },
      { "icon": "🍷", "en": "Premium Quality", "hi": "प्रीमियम क्वालिटी", "pa": "सबन ते खरी क्वालिटी" },
      { "icon": "🌾", "en": "Traditional Grains", "hi": "पारंपरिक अनाज", "pa": "पुराणा अनाज" },
      { "icon": "🔥", "en": "Tandoori Special", "hi": "तंदूरी स्पेशल", "pa": "तंदूरी स्पेशल" },
      { "icon": "🥘", "en": "Big Portions", "hi": "खाने की अच्छी मात्रा", "pa": "रज्जी करी खाणो" },
      { "icon": "🎂", "en": "Best Birthday Spot", "hi": "जन्मदिन के लिए उत्तम", "pa": "जन्मदिने तांई खरी जगह" },
      { "icon": "🕯️", "en": "Candle Light Dinner", "hi": "कैंडल लाइट डिनर", "pa": "शांति आला डिनर" },
      { "icon": "🍓", "en": "Seasonal Fruit Mix", "hi": "मौसमी फल", "pa": "बखते रे फल" },
      { "icon": "🧊", "en": "Chilled Beverages", "hi": "ठंडे पेय", "pa": "एकदम ठंडे शरबत" },
      { "icon": "🧺", "en": "Outdoor Seating", "hi": "बाहर बैठने की व्यवस्था", "pa": "बाहरे बैठणे दा जुगाड़" },
      { "icon": "👩‍🍳", "en": "Chef's Special", "hi": "शेफ की पसंद", "pa": "मिस्त्री दी पसंद" },
      { "icon": "🥢", "en": "Quick Snacks", "hi": "झटपट नाश्ता", "pa": "झटपट नाश्ता" },
      { "icon": "🧴", "en": "Hand Sanitizer Provided", "hi": "सैनिटाइज़र की सुविधा", "pa": "सफ़ाई दा इंतज़ाम" },
      { "icon": "🍽️", "en": "Fine Dining", "hi": "बढ़िया व्यवस्था", "pa": "खरा इंतज़ाम" },
      { "icon": "🍛", "en": "Spicy Curry", "hi": "मसालेदार करी", "pa": "चटपटी तरी" },
      { "icon": "🥨", "en": "Unique Menu", "hi": "अलग मेनू", "pa": "बखरा मेनू" },
      { "icon": "🧂", "en": "Customized Spice Level", "hi": "मिर्च अपने स्वाद अनुसार", "pa": "मिर्चां आपणे स्वादे मताबिक" },
      { "icon": "🥒", "en": "Crispy Salad", "hi": "ताज़ा सलाद", "pa": "ताजा सलाद" },
      { "icon": "🍬", "en": "Sweet Treats", "hi": "मीठी चीज़ें", "pa": "मीठा-मीठा" },
      { "icon": "🥛", "en": "Creamy Shakes", "hi": "मलाईदार शेक", "pa": "मलाई आले शेक" },
      { "icon": "🍖", "en": "Tender Meat", "hi": "नरम मीट", "pa": "नरम मीट" },
      { "icon": "🍱", "en": "Affordable Thali", "hi": "सस्ती थाली", "pa": "सस्ती ते खरी थाली" },
      { "icon": "🏠", "en": "Home-like Feel", "hi": "घर जैसा महसूस", "pa": "घरे जिया लग्गा" },
      { "icon": "🌳", "en": "Surrounded by Nature", "hi": "प्रकृति के बीच", "pa": "पेड़-पौधे रे बिच" },
      { "icon": "🏙️", "en": "City Center Location", "hi": "शहर के बीचों-बीच", "pa": "बाज़ारे रे बिच" },
      { "icon": "🏆", "en": "Award Winning Taste", "hi": "नामचीन स्वाद", "pa": "मशहूर स्वाद" }
    ],
    "hotels_and_stay": [
      { "icon": "🏔️", "en": "Snowy Peak View", "hi": "बर्फ़ीली चोटियों का दृश्य", "pa": "हिंम आली धार को नज़ारा" },
      { "icon": "🔥", "en": "Warm Fireplace", "hi": "गरम अंगीठी", "pa": "तपती अंगीठी" },
      { "icon": "🚿", "en": "Hot Water 24/7", "hi": "हर समय गरम पानी", "pa": "हर बखत ताता पाणी" },
      { "icon": "🛌", "en": "Cozy Blankets", "hi": "गरम और आरामदायक रज़ाई", "pa": "ताते ते कोमल लेफ़" },
      { "icon": "🛡️", "en": "Safe for Women", "hi": "महिलाओं के लिए सुरक्षित", "pa": "जणाणियां तांई सुरक्षित" },
      { "icon": "📶", "en": "Strong Wi-Fi", "hi": "तेज़ वाई-फ़ाई", "pa": "तेज़ इंटरनेट" },
      { "icon": "🍳", "en": "Home-made Breakfast", "hi": "घर जैसा नाश्ता", "pa": "घरे जिया नाश्ता" },
      { "icon": "🚶", "en": "Near Main Mall Road", "hi": "मॉल रोड के पास", "pa": "मॉल रोड रे नेड़े" },
      { "icon": "🌲", "en": "Peaceful Pine Forest", "hi": "शांत चीड़ का जंगल", "pa": "सुणसाण चिल को बण" },
      { "icon": "🅿️", "en": "Secure Parking", "hi": "सुरक्षित पार्किंग", "pa": "गाड़ी तांई सुरक्षित जगह" },
      { "icon": "👔", "en": "Polite Staff", "hi": "विनम्र कर्मचारी", "pa": "मिठु बोलणे आले लोग" },
      { "icon": "🧹", "en": "Spotless Linen", "hi": "साफ़ चादरें", "pa": "साफ़-सुथरी चादरां" },
      { "icon": "🍎", "en": "Garden Access", "hi": "बगीचे की सुविधा", "pa": "बगीचे दी सैर" },
      { "icon": "🔔", "en": "Quick Room Service", "hi": "तेज़ रूम सर्विस", "pa": "झटपट सेवा" },
      { "icon": "🔇", "en": "Quiet Surroundings", "hi": "शांतिपूर्ण माहौल", "pa": "रोले-धप्पे ते दूर" },
      { "icon": "🏨", "en": "Modern Interior", "hi": "आधुनिक सजावट", "pa": "नवी सजावट" },
      { "icon": "🖼️", "en": "Local Art Decor", "hi": "स्थानीय कला", "pa": "इथै री कला" },
      { "icon": "🧸", "en": "Kids Play Area", "hi": "बच्चों के खेलने की जगह", "pa": "बालकां रे खेलणे दी जगह" },
      { "icon": "🎒", "en": "Luggage Storage", "hi": "सामान रखने की जगह", "pa": "सामान तांई जगह" },
      { "icon": "🌅", "en": "Sunset Balcony", "hi": "सूर्यास्त का नज़ारा", "pa": "डूबदे सुरज को नजारा" },
      { "icon": "🪟", "en": "Wide Windows", "hi": "बड़ी खिड़कियाँ", "pa": "बड्डी खिडकियां" },
      { "icon": "🧘", "en": "Meditation Space", "hi": "ध्यान लगाने की जगह", "pa": "शांति दी जगह" },
      { "icon": "🍵", "en": "Welcome Drink", "hi": "स्वागत ड्रिंक", "pa": "आओ-भगत आला शरबत" },
      { "icon": "🕯️", "en": "Power Backup", "hi": "बिजली बैकअप", "pa": "बिजली दा पूरा इंतज़ाम" },
      { "icon": "🛀", "en": "Clean Bathroom", "hi": "साफ़ बाथरूम", "pa": "सुथरा गुसलखाना" },
      { "icon": "🧺", "en": "Laundry Service", "hi": "कपड़े धोने की सेवा", "pa": "कपड़े धोणे दी सेवा" },
      { "icon": "🛌", "en": "Firm Mattress", "hi": "आरामदायक गद्दा", "pa": "खरा गद्दा" },
      { "icon": "🥿", "en": "Slippers Provided", "hi": "चप्पल की सुविधा", "pa": "चप्पलां दा इंतज़ाम" },
      { "icon": "📦", "en": "Spacious Wardrobe", "hi": "बड़ी अलमारी", "pa": "बड्डी अलमारी" },
      { "icon": "📺", "en": "Smart TV", "hi": "स्मार्ट टीवी", "pa": "स्मार्ट टीवी" },
      { "icon": "🔌", "en": "Universal Outlets", "hi": "चार्जिंग पॉइंट", "pa": "चार्जिंग पॉइंट" },
      { "icon": "🧖", "en": "Sauna/Steam", "hi": "स्टीम बाथ", "pa": "भाप आला स्नान" },
      { "icon": "🚕", "en": "Taxi on Call", "hi": "टैक्सी की सुविधा", "pa": "टैक्सी दा बुलाबा" },
      { "icon": "🗺️", "en": "Tour Desk", "hi": "टूर डेस्क", "pa": "घूमणे री जानकारी" },
      { "icon": "🔐", "en": "Safe Locker", "hi": "तिजोरी", "pa": "सुरक्षित लॉकर" },
      { "icon": "👟", "en": "Morning Walk Path", "hi": "टहलने का रास्ता", "pa": "सैरे दा रस्ता" },
      { "icon": "💐", "en": "Fresh Flowers", "hi": "ताज़ा फूल", "pa": "ताजे फुल्ल" },
      { "icon": "🥤", "en": "Mini Fridge", "hi": "छोटा फ्रिज", "pa": "निक्का फ्रिज" },
      { "icon": "🥪", "en": "Packed Lunch", "hi": "पैक्ड लंच", "pa": "बन्ने दा खाणो" },
      { "icon": "🌦️", "en": "Weather Updates", "hi": "मौसम की जानकारी", "pa": "मौसमे री खबर" },
      { "icon": "💎", "en": "Luxury Vibe", "hi": "शानदार अनुभव", "pa": "बड्डा ठाठ-बाठ" },
      { "icon": "🏠", "en": "Heritage Property", "hi": "पुश्तैनी इमारत", "pa": "पुराणी कोठी" },
      { "icon": "🍂", "en": "Autumn View", "hi": "पतझड़ का दृश्य", "pa": "पतझड़ को नजारा" },
      { "icon": "🌸", "en": "Spring Bloom", "hi": "बहार का मौसम", "pa": "बहार को बखत" },
      { "icon": "🧗", "en": "Nearby Trekking", "hi": "पास में ट्रेकिंग", "pa": "नेड़े ही ट्रेकिंग" },
      { "icon": "📞", "en": "Helpful Reception", "hi": "मददगार रिसेप्शन", "pa": "मददगार लोग" },
      { "icon": "🍽️", "en": "Open Air Dining", "hi": "खुले में खाना", "pa": "बाहरे खाणो" },
      { "icon": "🥂", "en": "Perfect for Couples", "hi": "जोड़ों के लिए उत्तम", "pa": "जोड़ियाँ तांई खरा" },
      { "icon": "🐾", "en": "Pet Allowed", "hi": "पालतू जानवर ला सकते हैं", "pa": "कुत्ते-बिल्लियाँ तांई इजाजत" },
      { "icon": "🧼", "en": "Good Toiletries", "hi": "साबुन-शैम्पू की सुविधा", "pa": "नहाणे-धोणे दा सामान" },
      { "icon": "💧", "en": "Drinking Water", "hi": "पीने का साफ़ पानी", "pa": "पीणे दा सुथरा पाणी" },
      { "icon": "🛣️", "en": "Highway Access", "hi": "हाइवे के पास", "pa": "सड़कै रे नेड़े" },
      { "icon": "💸", "en": "Low Price Stay", "hi": "कम दाम में स्टे", "pa": "सस्ता ते खरा" },
      { "icon": "🏠", "en": "Homestay Feel", "hi": "होमस्टे जैसा", "pa": "आपणे घरे जिया" },
      { "icon": "🌳", "en": "Eco-Friendly", "hi": "पर्यावरण के अनुकूल", "pa": "हरियाली तांई खरा" },
      { "icon": "🤝", "en": "Honest Reviews", "hi": "सच्ची समीक्षा", "pa": "खरी गल्लां" },
      { "icon": "🛌", "en": "Extra Bed Available", "hi": "अतिरिक्त बिस्तर", "pa": "एक और बिस्तर" },
      { "icon": "☕", "en": "Electric Kettle", "hi": "इलेक्ट्रिक केतली", "pa": "चाह बणाणे री मशीन" },
      { "icon": "⭐", "en": "Highly Recommended", "hi": "ज़रूर आएँ", "pa": "इथै जरूर ओणा" },
      { "icon": "✨", "en": "Magical Stay", "hi": "जादुई अनुभव", "pa": "बड्डा सुणा अनुभव" }
    ],
    "travel_and_tourism": [
      { "icon": "🚐", "en": "Safe Hill Driving", "hi": "पहाड़ों में सुरक्षित ड्राइविंग", "pa": "पहाड़ा दी सुरक्षित ड्राइवरी" },
      { "icon": "🗺️", "en": "Expert Local Guide", "hi": "अनुभवी स्थानीय गाइड", "pa": "इथै दा सयाणो गाइड" },
      { "icon": "🥾", "en": "Great Trekking Route", "hi": "ट्रेकिंग के लिए बढ़िया रास्ता", "pa": "पैदल चलणे दा खरा रस्ता" },
      { "icon": "🏍️", "en": "Well Maintained Bikes", "hi": "अच्छी हालत में बाइक", "pa": "खरी कंडीशन दी बाइक" },
      { "icon": "⏰", "en": "Always Punctual", "hi": "समय के पाबंद", "pa": "बखत दा पाबंद" },
      { "icon": "💎", "en": "Hidden Gem Spot", "hi": "अनछुई सुंदर जगह", "pa": "लुक्की दी सुणी जगह" },
      { "icon": "📸", "en": "Best Photo Points", "hi": "फोटो खींचने की अच्छी जगह", "pa": "फोटो तांई खरी जगह" },
      { "icon": "🎒", "en": "Adventure Ready", "hi": "रोमांच के लिए तैयार", "pa": "मौज-मस्ती तांई तैयार" },
      { "icon": "🚕", "en": "Fair Taxi Rates", "hi": "टैक्सी का सही दाम", "pa": "टैक्सिए दा सई मोल" },
      { "icon": "⛺", "en": "Starry Night Camping", "hi": "तारों भरी रात और कैंपिंग", "pa": "तारों आली रात ते कैंपिंग" },
      { "icon": "🚠", "en": "Must Try Ropeway", "hi": "रोपवे ज़रूर आज़माएँ", "pa": "उडन खटोले दा मजा" },
      { "icon": "🦅", "en": "Paragliding Joy", "hi": "पैराग्लाइडिंग का मज़ा", "pa": "हवा विच उडणे दा मजा" },
      { "icon": "💧", "en": "Pure Waterfall", "hi": "सुंदर झरना", "pa": "सुणा चशमा" },
      { "icon": "🏛️", "en": "Heritage Tour", "hi": "विरासत की सैर", "pa": "पुराणी यादें री सैर" },
      { "icon": "🦜", "en": "Bird Watching", "hi": "पक्षियों को देखना", "pa": "चिड़ियाँ जो देखणा" },
      { "icon": "🎒", "en": "Solo Traveler Friendly", "hi": "अकेले यात्रियों के लिए", "pa": "कल्ला मुसाफिर तांई" },
      { "icon": "🧗", "en": "Challenging Climb", "hi": "कठिन चढ़ाई", "pa": "औखी चढ़ाई" },
      { "icon": "🏔️", "en": "Snow Activities", "hi": "बर्फ़ की गतिविधियाँ", "pa": "हिंम विच खेलणा" },
      { "icon": "🛕", "en": "Spiritual Vibe", "hi": "आध्यात्मिक शांति", "pa": "धार्मिक शांति" },
      { "icon": "🍃", "en": "Fresh Mountain Air", "hi": "पहाड़ों की ताज़ी हवा", "pa": "पहाड़ा दी ठंडी हवा" },
      { "icon": "🤝", "en": "Trustworthy Agency", "hi": "भरोसेमंद एजेंसी", "pa": "विस्वासिलो एजेंसी" },
      { "icon": "🛶", "en": "River Rafting", "hi": "रिवर राफ्टिंग", "pa": "पाणी विच राफ्टिंग" },
      { "icon": "🚲", "en": "Cycle Rental", "hi": "साइकिल रेंटल", "pa": "साइकिल दा किराया" },
      { "icon": "🚗", "en": "Clean Car Condition", "hi": "साफ़ गाड़ी", "pa": "सुथरी ते खरी गाड़ी" },
      { "icon": "🔦", "en": "Night Trekking", "hi": "रात की ट्रेकिंग", "pa": "राती री ट्रेकिंग" },
      { "icon": "🌲", "en": "Forest Bathing", "hi": "जंगल की सैर", "pa": "बणी री सैर" },
      { "icon": "🍎", "en": "Orchard Visit", "hi": "बगीचे की सैर", "pa": "बगीचे दा फेरा" },
      { "icon": "🌦️", "en": "Weather Guidance", "hi": "मौसम की सलाह", "pa": "मौसमे री जानकारी" },
      { "icon": "💰", "en": "No Hidden Costs", "hi": "कोई अतिरिक्त खर्चा नहीं", "pa": "कोई फालतू खर्चा नी" },
      { "icon": "🎫", "en": "Easy Booking", "hi": "आसान बुकिंग", "pa": "सजिलो बुकिंग" },
      { "icon": "🎢", "en": "Fun for Kids", "hi": "बच्चों के लिए मज़ा", "pa": "बालकां तांई मजा" },
      { "icon": "🐴", "en": "Horse Riding", "hi": "घुड़सवारी", "pa": "घोड़े री सवारी" },
      { "icon": "🔭", "en": "Telescope View", "hi": "दूरबीन से नज़ारा", "pa": "दूरबीने सती नजारा" },
      { "icon": "🎣", "en": "Fishing Spot", "hi": "मछली पकड़ने की जगह", "pa": "मछली पकड़णे दी जगह" },
      { "icon": "🧘", "en": "Yoga Retreat", "hi": "योग शिविर", "pa": "योगा दा कैंप" },
      { "icon": "🔥", "en": "Bonfire Night", "hi": "अलाव और मस्ती", "pa": "राती जो आग ते मस्ती" },
      { "icon": "🥾", "en": "Sturdy Rental Gear", "hi": "मज़बूत किराए का सामान", "pa": "किराये दा तगड़ा सामान" },
      { "icon": "🚶", "en": "Guided City Walk", "hi": "गाइड के साथ सैर", "pa": "गाइडे सती सैर" },
      { "icon": "🚙", "en": "Off-roading Experience", "hi": "ऑफ-रोडिंग का मज़ा", "pa": "कच्चे रस्ते दा मजा" },
      { "icon": "🏘️", "en": "Village Life Tour", "hi": "गाँव की सैर", "pa": "ग्रां री सैर" },
      { "icon": "🍵", "en": "Tea Garden Tour", "hi": "चाय के बागान", "pa": "चाह रे बगीचे" },
      { "icon": "📸", "en": "Perfect Selfie Spot", "hi": "सेल्फी के लिए उत्तम", "pa": "सेल्फी तांई खरी जगह" },
      { "icon": "🛒", "en": "Local Handicraft Info", "hi": "हस्तशिल्प की जानकारी", "pa": "हाथक बणाई चीज़ें" },
      { "icon": "🦌", "en": "Wildlife Sighting", "hi": "वन्यजीव दर्शन", "pa": "जंगली जनावर देखणा" },
      { "icon": "🎒", "en": "Group Tour Expert", "hi": "ग्रुप टूर एक्सपर्ट", "pa": "टोली तांई सयाणो" },
      { "icon": "🛤️", "en": "Toy Train Journey", "hi": "टॉय ट्रेन का सफर", "pa": "निक्की ट्रेन दा सफर" },
      { "icon": "👟", "en": "Easy Trail", "hi": "आसान रास्ता", "pa": "सजिलो रस्ता" },
      { "icon": "🗺️", "en": "Detailed Maps", "hi": "नक्शे की जानकारी", "pa": "नक्शे दी जानकारी" },
      { "icon": "🛡️", "en": "Safe Equipment", "hi": "सुरक्षित उपकरण", "pa": "सुरक्षित सामान" },
      { "icon": "🗣️", "en": "Multi-language Guide", "hi": "कई भाषाओं का ज्ञान", "pa": "घणी बोलियां दा सयाणो" },
      { "icon": "⛺", "en": "Wild Camping", "hi": "खुली कैंपिंग", "pa": "खुली कैंपिंग" },
      { "icon": "🌅", "en": "Sunrise Point", "hi": "सूर्योदय का स्थान", "pa": "सुरज निकले को नजारा" },
      { "icon": "🍱", "en": "Meal Included", "hi": "खाना शामिल है", "pa": "खाणो सती ही है" },
      { "icon": "🛑", "en": "Frequent Stops", "hi": "जगह-जगह रुकना", "pa": "थौड़-थौड़ रुकणा" },
      { "icon": "🔋", "en": "Power Supply in Camps", "hi": "कैंप में बिजली", "pa": "कैंपे विच बिजली" },
      { "icon": "🧥", "en": "Rental Jackets", "hi": "किराए की जैकेट", "pa": "किराये री कोर्टी" },
      { "icon": "📱", "en": "GPS Tracking", "hi": "जीपीएस सुविधा", "pa": "लोकेशन दी सुविधा" },
      { "icon": "🩹", "en": "First Aid Ready", "hi": "प्राथमिक चिकित्सा", "pa": "दवाई-बूटी दा इंतज़ाम" },
      { "icon": "🌟", "en": "Memorable Trip", "hi": "यादगार यात्रा", "pa": "बड्डा सुणा फेरा" },
      { "icon": "🛣️", "en": "Smooth Journey", "hi": "सुखद यात्रा", "pa": "सुख आला सफर" }
    ],
    "local_shops": [
      { "icon": "🧶", "en": "Pure Wool Items", "hi": "शुद्ध ऊनी सामान", "pa": "खरा ऊणी सामान" },
      { "icon": "🎁", "en": "Unique Souvenirs", "hi": "अनोखे उपहार", "pa": "अनोखी सौगात" },
      { "icon": "🏷️", "en": "Fixed & Fair Price", "hi": "उचित और तय दाम", "pa": "एकदम सई दाम" },
      { "icon": "📱", "en": "Latest Models", "hi": "नये मॉडल", "pa": "नवे मॉडल" },
      { "icon": "💯", "en": "Original Products", "hi": "असली सामान", "pa": "खरा ते असली सौदा" },
      { "icon": "🤝", "en": "Honest Shopkeeper", "hi": "ईमानदार दुकानदार", "pa": "ईमानदार हट्टी आला" },
      { "icon": "🧺", "en": "Handicrafts", "hi": "हस्तशिल्प", "pa": "हाथक बणाई चीज़ें" },
      { "icon": "🧺", "en": "Fresh Groceries", "hi": "ताज़ा राशन", "pa": "ताजा राशन" },
      { "icon": "👕", "en": "Trial Room Available", "hi": "ट्रायल रूम", "pa": "कपड़े चैक करणे री जगह" },
      { "icon": "📦", "en": "Good Packaging", "hi": "अच्छी पैकिंग", "pa": "खरी पैकिंग" },
      { "icon": "🛍️", "en": "Wide Variety", "hi": "ढेर सारे विकल्प", "pa": "बड्डा सारा सामान" },
      { "icon": "⚡", "en": "Fast Checkout", "hi": "जल्दी बिलिंग", "pa": "झटपट बिल" },
      { "icon": "💳", "en": "Digital Payment OK", "hi": "ऑनलाइन पेमेंट उपलब्ध", "pa": "फोन पे/कार्ड चालदा" },
      { "icon": "🍎", "en": "Local Fruit/Veg", "hi": "स्थानीय फल-सब्ज़ी", "pa": "इथै रे फल-सब्जी" },
      { "icon": "🧥", "en": "Handwoven Shawls", "hi": "हाथ की बुनी शॉल", "pa": "हाथक बुणी लोई" },
      { "icon": "🍬", "en": "Traditional Sweets", "hi": "पारंपरिक मिठाइयाँ", "pa": "पुराणी मिठाइयां" },
      { "icon": "🏠", "en": "Homely Vibe", "hi": "घरेलू अहसास", "pa": "घरे जिया माहौल" },
      { "icon": "🪵", "en": "Wooden Artifacts", "hi": "लकड़ी का सामान", "pa": "काठ दा सामान" },
      { "icon": "🧴", "en": "Herbal Products", "hi": "हर्बल सामान", "pa": "जड़ी-बूटी आला सामान" },
      { "icon": "📅", "en": "Always Fresh Stock", "hi": "हमेशा नया स्टॉक", "pa": "हर बखत नवा सामान" },
      { "icon": "👠", "en": "Quality Footwear", "hi": "अच्छे जूते", "pa": "खरे जूते-चप्पलां" },
      { "icon": "💍", "en": "Local Jewelry", "hi": "स्थानीय गहने", "pa": "इथै रे गहणे" },
      { "icon": "📚", "en": "Knowledgeable Staff", "hi": "जानकार कर्मचारी", "pa": "सयाणे लोग" },
      { "icon": "🕰️", "en": "Antique Collection", "hi": "पुरानी चीज़ें", "pa": "पुराणी चीज़ें" },
      { "icon": "🍼", "en": "Baby Products", "hi": "बच्चों का सामान", "pa": "निक्के बालकां दा सामान" },
      { "icon": "🥦", "en": "Organic Farm Fresh", "hi": "खेत से ताज़ा", "pa": "खेती दा ताजा सामान" },
      { "icon": "🔩", "en": "Hardware Expert", "hi": "हार्डवेयर की जानकारी", "pa": "हार्डवेयर दा सयाणो" },
      { "icon": "🧼", "en": "Clean Store", "hi": "साफ़ दुकान", "pa": "सुथरी हट्टी" },
      { "icon": "🪑", "en": "Furniture Range", "hi": "फर्नीचर के विकल्प", "pa": "फर्नीचर दा सामान" },
      { "icon": "📷", "en": "Electronics Hub", "hi": "इलेक्ट्रॉनिक्स दुकान", "pa": "बिजली दा सामान" },
      { "icon": "💊", "en": "Pharmacy Support", "hi": "दवाइयों की उपलब्धता", "pa": "दवाई दी हट्टी" },
      { "icon": "🚜", "en": "Agri Supplies", "hi": "खेती का सामान", "pa": "खेती-बाड़ी दा सामान" },
      { "icon": "🧣", "en": "Mufflers & Caps", "hi": "मफलर और टोपी", "pa": "मफलर ते टोपी" },
      { "icon": "🍯", "en": "Pure Honey/Ghee", "hi": "शुद्ध शहद और घी", "pa": "खरा शहद ते घ्यू" },
      { "icon": "🎒", "en": "Travel Gear Shop", "hi": "यात्रा का सामान", "pa": "सफरे दा सामान" },
      { "icon": "🔌", "en": "Reliable Gadgets", "hi": "भरोसेमंद गैजेट्स", "pa": "विस्वासिलो सामान" },
      { "icon": "💎", "en": "Authentic Stones", "hi": "असली पत्थर/नग", "pa": "असली नग" },
      { "icon": "🌾", "en": "Local Pulses/Dal", "hi": "स्थानीय दालें", "pa": "इथै दी दालां" },
      { "icon": "🍪", "en": "Bakery Delights", "hi": "बेकरी का सामान", "pa": "बेकरी दा सामान" },
      { "icon": "🥨", "en": "Unique Snacks", "hi": "अनोखे स्नैक्स", "pa": "अनोखे स्नैक्स" },
      { "icon": "🎨", "en": "Artist Supplies", "hi": "कला का सामान", "pa": "कलाकारी दा सामान" },
      { "icon": "🧸", "en": "Toy Paradise", "hi": "खिलौनों की दुनिया", "pa": "खेळणे दी दुनिया" },
      { "icon": "👔", "en": "Formal Wear", "hi": "फॉर्मल कपड़े", "pa": "दफ्तरे आले कपड़े" },
      { "icon": "💃", "en": "Traditional Dress", "hi": "पारंपरिक वेशभूषा", "pa": "पुराणा पहनावा" },
      { "icon": "💸", "en": "Budget Friendly", "hi": "बजट में", "pa": "सस्ता सामान" },
      { "icon": "🚚", "en": "Home Delivery", "hi": "घर तक डिलीवरी", "pa": "घरे तक सामान" },
      { "icon": "🔄", "en": "Easy Exchange", "hi": "आसान बदलाव", "pa": "सामान बदली जाणा" },
      { "icon": "☕", "en": "Local Tea Leaf", "hi": "स्थानीय चाय पत्ती", "pa": "इथै दी चाह पत्ती" },
      { "icon": "🥒", "en": "Handmade Pickle", "hi": "हाथ का अचार", "pa": "हाथक बणाया अचाण" },
      { "icon": "🕯️", "en": "Decorative Candles", "hi": "सजावटी मोमबत्तियाँ", "pa": "सजावट दी बत्तियां" },
      { "icon": "🍳", "en": "Kitchen Utensils", "hi": "रसोई के बर्तन", "pa": "चौके रे भांडे" },
      { "icon": "⛺", "en": "Camping Tents", "hi": "कैंपिंग टेंट", "pa": "कैंपिंग टेंट" },
      { "icon": "🧴", "en": "Body Care Items", "hi": "त्वचा की देखभाल", "pa": "शरीर तांई क्रीम-तेल" },
      { "icon": "👟", "en": "Sports Gear", "hi": "खेल का सामान", "pa": "खेळां दा सामान" },
      { "icon": "💼", "en": "Leather Bags", "hi": "चमड़े के बैग", "pa": "चमड़े रे बैग" },
      { "icon": "🎁", "en": "Gift Wrapping", "hi": "गिफ्ट पैकिंग", "pa": "गिफ्ट पैकिंग" },
      { "icon": "🛒", "en": "Well Organized", "hi": "सुव्यवस्थित", "pa": "सलीके सती सामान" },
      { "icon": "🚪", "en": "Easy Access", "hi": "आसान पहुँच", "pa": "नेड़े ही है" },
      { "icon": "🌟", "en": "Best in Town", "hi": "शहर में सबसे अच्छा", "pa": "सबन ते खरी हट्टी" },
      { "icon": "🛍️", "en": "Happy Shopping", "hi": "खुशनुमा खरीदारी", "pa": "खरी खरीदारी" }
    ],
    "healthcare": [
      { "icon": "👨‍⚕️", "en": "Experienced Doctor", "hi": "अनुभवी डॉक्टर", "pa": "सयाणो डॉक्टर" },
      { "icon": "⏱️", "en": "Quick Emergency Care", "hi": "तुरंत आपातकालीन सेवा", "pa": "झटपट इलाज" },
      { "icon": "🔬", "en": "Accurate Reports", "hi": "सटीक रिपोर्ट", "pa": "सई रिपोर्ट" },
      { "icon": "🏥", "en": "Clean Facility", "hi": "साफ़ अस्पताल", "pa": "सुथरा हस्पताल" },
      { "icon": "💊", "en": "Always Stocked", "hi": "दवाइयाँ हमेशा उपलब्ध", "pa": "दवाई हर बखत मिलदी" },
      { "icon": "💙", "en": "Kind Nursing Staff", "hi": "दयालु नर्स", "pa": "भली नर्सां" },
      { "icon": "🗣️", "en": "Clear Explanations", "hi": "साफ़ सलाह", "pa": "खरी गल्लां" },
      { "icon": "🦷", "en": "Painless Dentist", "hi": "दर्द रहित इलाज", "pa": "बिना पीड़ा दा इलाज" },
      { "icon": "🧪", "en": "Modern Lab", "hi": "आधुनिक लैब", "pa": "नवी लैब" },
      { "icon": "🚑", "en": "Fast Ambulance", "hi": "तेज़ एम्बुलेंस", "pa": "तेज़ एम्बुलेंस" },
      { "icon": "🩹", "en": "Gentle Dressing", "hi": "आरामदायक पट्टी", "pa": "प्यारे सती पट्टी" },
      { "icon": "📅", "en": "Easy Appointment", "hi": "आसान अपॉइंटमेंट", "pa": "सजिलो टाइम मिलणा" },
      { "icon": "💸", "en": "Reasonable Fees", "hi": "उचित फीस", "pa": "सई फीस" },
      { "icon": "🦽", "en": "Wheelchair Access", "hi": "व्हीलचेयर की सुविधा", "pa": "व्हीलचेयर दा रस्ता" },
      { "icon": "👂", "en": "Patient Listener", "hi": "ध्यान से सुनते हैं", "pa": "धीरज सती सुणदे" },
      { "icon": "👶", "en": "Child Specialist", "hi": "बच्चों के डॉक्टर", "pa": "बालकां रे डॉक्टर" },
      { "icon": "🤰", "en": "Gynae Care", "hi": "स्त्री रोग विशेषज्ञ", "pa": "जणाणियां रे डॉक्टर" },
      { "icon": "🦴", "en": "Bone Expert", "hi": "हड्डियों के डॉक्टर", "pa": "हड्डियां रे सयाणे" },
      { "icon": "👁️", "en": "Eye Care Specialist", "hi": "आँखों के डॉक्टर", "pa": "अक्खां रे डॉक्टर" },
      { "icon": "🩺", "en": "Routine Checkup", "hi": "नियमित जांच", "pa": "रोज री जांच" },
      { "icon": "🧴", "en": "Skin Specialist", "hi": "त्वचा विशेषज्ञ", "pa": "चमड़ी रे सयाणे" },
      { "icon": "🥗", "en": "Diet Consultation", "hi": "डाइट सलाह", "pa": "खाणे-पीणे री सलाह" },
      { "icon": "🧘", "en": "Mental Wellness", "hi": "मानसिक स्वास्थ्य", "pa": "दिमागी शांति" },
      { "icon": "💉", "en": "Quick Vaccination", "hi": "जल्दी टीकाकरण", "pa": "झटपट टीका" },
      { "icon": "🛏️", "en": "Comfortable Ward", "hi": "आरामदायक वार्ड", "pa": "खरा वार्ड" },
      { "icon": "🌡️", "en": "Fever Specialist", "hi": "बुखार विशेषज्ञ", "pa": "तापे रे सयाणे" },
      { "icon": "🛡️", "en": "Highly Hygienic", "hi": "बहुत साफ़-सुथरा", "pa": "बड्डा सुथरा" },
      { "icon": "📈", "en": "Advanced Tech", "hi": "नयी तकनीक", "pa": "नवी मशीनें" },
      { "icon": "📞", "en": "Tele-Consultation", "hi": "फ़ोन पर सलाह", "pa": "फोने पर सलाह" },
      { "icon": "🤝", "en": "Trustworthy Advice", "hi": "भरोसेमंद सलाह", "pa": "विस्वासिलो सलाह" },
      { "icon": "🧊", "en": "Blood Bank Support", "hi": "ब्लड बैंक सुविधा", "pa": "खून दा इंतज़ाम" },
      { "icon": "🧼", "en": "Sanitized Area", "hi": "साफ़ वातावरण", "pa": "साफ़ माहौल" },
      { "icon": "👔", "en": "Professionalism", "hi": "व्यावसायिकता", "pa": "तरीके आला काम" },
      { "icon": "🚫", "en": "No Waiting", "hi": "इंतज़ार नहीं", "pa": "इंतज़ार नी करना" },
      { "icon": "🚲", "en": "Physiotherapy Help", "hi": "फिजियोथेरेपी सहायता", "pa": "कसरते दी मदद" },
      { "icon": "🏥", "en": "Large Facility", "hi": "बड़ा अस्पताल", "pa": "बड्डा हस्पताल" },
      { "icon": "💎", "en": "Premium Care", "hi": "शानदार देखभाल", "pa": "खरी देखभाल" },
      { "icon": "📱", "en": "Digital Records", "hi": "डिजिटल रिकॉर्ड", "pa": "कम्प्यूटरे विच खबर" },
      { "icon": "🚶", "en": "Walk-in Facility", "hi": "बिना अपॉइंटमेंट", "pa": "सीधे ही इलाज" },
      { "icon": "🫀", "en": "Heart Specialist", "hi": "दिल के डॉक्टर", "pa": "दिल्ले रे सयाणे" },
      { "icon": "🧠", "en": "Brain Expert", "hi": "न्यूरो विशेषज्ञ", "pa": "दिमागे रे सयाणे" },
      { "icon": "🍬", "en": "Diabetic Care", "hi": "शुगर का इलाज", "pa": "शुगरे दा इलाज" },
      { "icon": "👂", "en": "ENT Specialist", "hi": "कान-नाक-गला", "pa": "कन्न-नाक-गले रे सयाणे" },
      { "icon": "🧪", "en": "Home Sample Pick", "hi": "घर से जांच", "pa": "घरे ते जांच" },
      { "icon": "💊", "en": "Discounted Meds", "hi": "दवाइयों पर छूट", "pa": "दवाइयां विच छूट" },
      { "icon": "😷", "en": "Safety Protocol", "hi": "सुरक्षा नियम", "pa": "बचाओ रे नियम" },
      { "icon": "🏥", "en": "Government Support", "hi": "सरकारी सहायता", "pa": "सरकारी मदद" },
      { "icon": "🌟", "en": "Top Rated Doctor", "hi": "प्रसिद्ध डॉक्टर", "pa": "मशहूर डॉक्टर" },
      { "icon": "🧥", "en": "Proper Uniform", "hi": "वर्दी में स्टाफ", "pa": "वर्दी विच लोग" },
      { "icon": "📋", "en": "Clear Billing", "hi": "साफ़ बिल", "pa": "साफ़ बिल" },
      { "icon": "🥤", "en": "Water Facility", "hi": "पानी की सुविधा", "pa": "पीणे दा पाणी" },
      { "icon": "🪑", "en": "Waiting Chairs", "hi": "बैठने की कुर्सियाँ", "pa": "बैठणे दी कुर्सियां" },
      { "icon": "🚪", "en": "Private Rooms", "hi": "प्राइवेट रूम", "pa": "आपणा कमरा" },
      { "icon": "🧴", "en": "Dermatology Care", "hi": "चर्म रोग", "pa": "चमड़ी दा इलाज" },
      { "icon": "👟", "en": "Post-Op Care", "hi": "ऑपरेशन के बाद की देखभाल", "pa": "ऑपरेशने बाद दी सेवा" },
      { "icon": "🏥", "en": "Multi-Specialty", "hi": "मल्टी-स्पेशलिटी", "pa": "हर बीमारी दा इलाज" },
      { "icon": "🛡️", "en": "Safe Environment", "hi": "सुरक्षित माहौल", "pa": "सुरक्षित माहौल" },
      { "icon": "📞", "en": "Follow-up Call", "hi": "बाद में संपर्क", "pa": "बाद विच पूछ-पड़ताल" },
      { "icon": "🙏", "en": "Life Saving", "hi": "जीवन रक्षक", "pa": "जिंदगी बचाणे आले" },
      { "icon": "🌟", "en": "Best Healthcare", "hi": "बेहतरीन स्वास्थ्य सेवा", "pa": "सबन ते खरी सेवा" }
    ],
    "personal_care": [
      { "icon": "✂️", "en": "Skilled Barber", "hi": "कुशल नाई", "pa": "हाथ दा सयाणो नाई" },
      { "icon": "🧖", "en": "Relaxing Facial", "hi": "आरामदायक फेशियल", "pa": "बड्डा सुकून आला फेशियल" },
      { "icon": "🌿", "en": "Herbal Beauty Products", "hi": "हर्बल ब्यूटी उत्पाद", "pa": "जड़ी-बूटियां आले सामान" },
      { "icon": "💅", "en": "Perfect Manicure", "hi": "शानदार मैनीक्योर", "pa": "नक्खां दी खरी सफाई" },
      { "icon": "🕊️", "en": "Peaceful Atmosphere", "hi": "शांत माहौल", "pa": "एकदम सुणसाण ते चैन" },
      { "icon": "🧼", "en": "Hygiene First", "hi": "साफ़-सफाई अव्वल", "pa": "सफ़ाई दा पूरा ध्यान" },
      { "icon": "✨", "en": "Trendy Haircut", "hi": "नया हेयरस्टाइल", "pa": "नवे जमाने दी कटिंग" },
      { "icon": "💆", "en": "Soothing Head Massage", "hi": "सिर की मालिश", "pa": "सिर दी मालिश ते चैन" },
      { "icon": "🎨", "en": "Expert Hair Color", "hi": "कुशल हेयर कलर", "pa": "वालां दा खरा रंग" },
      { "icon": "🤝", "en": "Friendly Stylist", "hi": "दोस्ताना स्टाइलिस्ट", "pa": "मिलनसार लोग" },
      { "icon": "⚡", "en": "Fast Service", "hi": "तेज़ सेवा", "pa": "झटपट काम" },
      { "icon": "💸", "en": "Affordable Beauty", "hi": "किफ़ायती पार्लर", "pa": "सस्ता ते खरा पार्लर" },
      { "icon": "🧖‍♀️", "en": "Luxury Spa Feel", "hi": "लक्जरी स्पा अनुभव", "pa": "बड्डा ठाठ-बाठ आला स्पा" },
      { "icon": "🚿", "en": "Steam & Sauna", "hi": "भाप स्नान", "pa": "भाप आला स्नान" },
      { "icon": "💄", "en": "Professional Makeup", "hi": "प्रोफेशनल मेकअप", "pa": "खरी सजावट" },
      { "icon": "🧴", "en": "Quality Lotions", "hi": "अच्छे लोशन", "pa": "खरे तेल-क्रीम" },
      { "icon": "🪒", "en": "Clean Shave", "hi": "साफ़ शेव", "pa": "सफ़ाचट शेव" },
      { "icon": "🧤", "en": "Sterilized Tools", "hi": "कीटाणुरहित औज़ार", "pa": "साफ़-सुथरे औज़ार" },
      { "icon": "👰", "en": "Bridal Specialist", "hi": "दुल्हन मेकअप विशेषज्ञ", "pa": "बेहटी दी सजावट तांई" },
      { "icon": "🌡️", "en": "Warm Towels", "hi": "गरम तौलिए", "pa": "ताता साफ़ा" },
      { "icon": "🪑", "en": "Comfortable Chairs", "hi": "आरामदायक कुर्सियां", "pa": "बैठणे तांई खरी कुर्सियां" },
      { "icon": "🚿", "en": "Hot Water Shower", "hi": "गरम पानी की सुविधा", "pa": "ताते पाणि दी सुविधा" },
      { "icon": "🧴", "en": "Organic Wax", "hi": "ऑर्गेनिक वैक्स", "pa": "खेती आली वैक्स" },
      { "icon": "👁️", "en": "Eyebrow Perfection", "hi": "सही थ्रेडिंग", "pa": "अक्खां दी खरी थ्रेडिंग" },
      { "icon": "🧔", "en": "Beard Grooming", "hi": "दाढ़ी की सेटिंग", "pa": "दाढ़ी दी खरी सेटिंग" },
      { "icon": "🕒", "en": "Open on Sundays", "hi": "रविवार को खुला", "pa": "एतवार जो भी खुला" },
      { "icon": "📅", "en": "Easy Booking", "hi": "आसान बुकिंग", "pa": "सजिलो बुकिंग" },
      { "icon": "👃", "en": "No Harsh Smells", "hi": "हल्की खुशबू", "pa": "मिठु खुशबू" },
      { "icon": "🧣", "en": "Neck Relaxation", "hi": "गर्दन की मालिश", "pa": "गले दी मालिश" },
      { "icon": "🧘", "en": "Zen Vibe", "hi": "सुकून भरा स्थान", "pa": "सुकूने दी जगह" },
      { "icon": "🚿", "en": "Clean Locker Rooms", "hi": "साफ़ लॉकर रूम", "pa": "सुथरा लॉकर" },
      { "icon": "💎", "en": "Worth Every Penny", "hi": "पैसा वसूल", "pa": "पूरा पैसा वसूल" },
      { "icon": "👟", "en": "Foot Massage", "hi": "पैरों की मालिश", "pa": "पैरां दी मालिश" },
      { "icon": "🧴", "en": "Sulfate Free Products", "hi": "केमिकल मुक्त", "pa": "बिना कैमिकले दा" },
      { "icon": "🧴", "en": "Premium Oils", "hi": "बेहतरीन तेल", "pa": "खरा तेल" },
      { "icon": "💆‍♀️", "en": "Deep Tissue Relief", "hi": "गहरी मालिश", "pa": "तगड़ी मालिश" },
      { "icon": "🧼", "en": "Fresh Gowns", "hi": "साफ़ गाउन", "pa": "साफ़ कपड़े" },
      { "icon": "📞", "en": "Friendly Callback", "hi": "मददगार कॉल", "pa": "खरी गल्लां" },
      { "icon": "🥤", "en": "Complimentary Tea", "hi": "मुफ्त चाय-पानी", "pa": "फ्री चाह-पाणी" },
      { "icon": "🧴", "en": "Anti-Aging Care", "hi": "झुर्रियों का इलाज", "pa": "झुर्रियां दा इलाज" },
      { "icon": "🌿", "en": "Ayurvedic Treatment", "hi": "आयुर्वेदिक इलाज", "pa": "देसी जड़ी-बूटियां" },
      { "icon": "💡", "en": "Bright Lighting", "hi": "अच्छी रोशनी", "pa": "खरी रौशनी" },
      { "icon": "🧣", "en": "Shoulder Massage", "hi": "कंधों की मालिश", "pa": "मोढ्यां दी मालिश" },
      { "icon": "🧴", "en": "Sensitive Skin Care", "hi": "कोमल त्वचा की देखभाल", "pa": "नरम चमड़ी तांई" },
      { "icon": "🎶", "en": "Soft Music", "hi": "धीमा संगीत", "pa": "मिठु गाणे" },
      { "icon": "🛡️", "en": "Safe Environment", "hi": "सुरक्षित माहौल", "pa": "सुरक्षित माहौल" },
      { "icon": "🚫", "en": "No Waiting Time", "hi": "प्रतीक्षा नहीं", "pa": "इंतज़ार नी करना" },
      { "icon": "🧺", "en": "Disposable Sheets", "hi": "डिस्पोजेबल शीट", "pa": "बदली होणे आली चादर" },
      { "icon": "💅", "en": "Nail Art", "hi": "नेल आर्ट", "pa": "नक्खां दी सजावट" },
      { "icon": "🎨", "en": "Creative Stylists", "hi": "रचनात्मक स्टाइलिस्ट", "pa": "कलाकार लोग" },
      { "icon": "💎", "en": "Luxury Brands Used", "hi": "ब्रांडेड सामान", "pa": "ब्रांडेड सामान" },
      { "icon": "🌟", "en": "High End Experience", "hi": "शानदार अनुभव", "pa": "बड्डा सुणा काम" },
      { "icon": "🚿", "en": "Clean Showers", "hi": "साफ़ शावर", "pa": "सुथरा स्नानघर" },
      { "icon": "🧴", "en": "Detox Treatment", "hi": "डिटॉक्स ट्रीटमेंट", "pa": "गंदगी दी सफ़ाई" },
      { "icon": "🧊", "en": "Cooling Pack", "hi": "ठंडा पैक", "pa": "ठंडा लेप" },
      { "icon": "🔥", "en": "Warm Stone Therapy", "hi": "गरम पत्थर थेरेपी", "pa": "ताते पत्थर दी मालिश" },
      { "icon": "🧘", "en": "Mindfulness", "hi": "दिमागी शांति", "pa": "मन दी शांति" },
      { "icon": "🤝", "en": "Attentive Staff", "hi": "ध्यान देने वाले लोग", "pa": "ध्यान रखणे आले लोग" },
      { "icon": "🌈", "en": "Vibrant Colors", "hi": "चमकदार रंग", "pa": "चमकीले रंग" },
      { "icon": "🏆", "en": "Best in Area", "hi": "इलाके में सबसे अच्छा", "pa": "इलाके विच सबन ते खरा" }
    ],
    "automotive": [
      { "icon": "🔧", "en": "Honest Mechanic", "hi": "ईमानदार मैकेनिक", "pa": "ईमानदार मिस्त्री" },
      { "icon": "⏱️", "en": "Quick Repair", "hi": "तुरंत मरम्मत", "pa": "झटपट काम" },
      { "icon": "💵", "en": "Fair Pricing", "hi": "उचित दाम", "pa": "सई दाम" },
      { "icon": "⚙️", "en": "Genuine Spare Parts", "hi": "असली पुर्जे", "pa": "असली सामान" },
      { "icon": "🤝", "en": "Helpful Service", "hi": "मददगार सर्विस", "pa": "मददगार लोग" },
      { "icon": "🚗", "en": "Excellent Car Wash", "hi": "शानदार धुलाई", "pa": "खरी धुलाई" },
      { "icon": "⛽", "en": "Full Fuel Delivery", "hi": "तेल की पूरी मात्रा", "pa": "पूरा तेल" },
      { "icon": "🛞", "en": "Wheel Alignment", "hi": "व्हील अलाइनमेंट", "pa": "टायरां दी सैटिंग" },
      { "icon": "🔋", "en": "Fast Battery Charge", "hi": "बैटरी चार्जिंग", "pa": "बैटरी चार्जिंग" },
      { "icon": "🧼", "en": "Interior Cleaning", "hi": "अंदर की सफ़ाई", "pa": "अंदरै दी सफ़ाई" },
      { "icon": "🎨", "en": "Clean Paint Job", "hi": "शानदार पेंट", "pa": "खरा रंग-पेंट" },
      { "icon": "🔨", "en": "Denting Expert", "hi": "डेंटिंग विशेषज्ञ", "pa": "डेंटिंग दा सयाणो" },
      { "icon": "🏍️", "en": "Best Bike Service", "hi": "बाइक सर्विस के लिए बढ़िया", "pa": "बाइके तांई बड्डा खरा" },
      { "icon": "🛣️", "en": "Highway Support", "hi": "हाइवे सहायता", "pa": "सड़कै पर मदद" },
      { "icon": "📱", "en": "Easy Status Updates", "hi": "काम की जानकारी", "pa": "कामे दी खबर" },
      { "icon": "🚿", "en": "Underbody Wash", "hi": "नीचे की धुलाई", "pa": "थल्ले दी धुलाई" },
      { "icon": "🧴", "en": "Wax Polish", "hi": "वैक्स पॉलिश", "pa": "चमकीली पॉलिश" },
      { "icon": "🔌", "en": "Electrical Repairs", "hi": "बिजली का काम", "pa": "करंटे दा काम" },
      { "icon": "🛢️", "en": "Engine Oil Change", "hi": "इंजन ऑयल बदलाव", "pa": "इंजन दा तेल" },
      { "icon": "🌬️", "en": "AC Gas Refill", "hi": "एसी गैस रिफिल", "pa": "एसी दी गैस" },
      { "icon": "🔩", "en": "Bolt Tightening", "hi": "नट-बोल्ट कसना", "pa": "नट-बोल्ट कसणे" },
      { "icon": "🪞", "en": "Mirror Replacement", "hi": "शीशा बदलना", "pa": "शीशा बदली" },
      { "icon": "🔦", "en": "Headlight Restoration", "hi": "लाइट मरम्मत", "pa": "बत्तियां दा काम" },
      { "icon": "🚨", "en": "Emergency Towing", "hi": "गाड़ी खींचने की सुविधा", "pa": "गाड़ी खींचणा" },
      { "icon": "🛞", "en": "Tire Puncture Fix", "hi": "पंचर मरम्मत", "pa": "पंचर दा काम" },
      { "icon": "🛡️", "en": "Reliable Work", "hi": "भरोसेमंद काम", "pa": "विस्वासिलो काम" },
      { "icon": "📞", "en": "Quick Response", "hi": "तुरंत जवाब", "pa": "झटपट सुणवाई" },
      { "icon": "🛠️", "en": "All Parts Available", "hi": "सारे सामान उपलब्ध", "pa": "सब सामान मिलदा" },
      { "icon": "🚛", "en": "Heavy Vehicle Support", "hi": "भारी वाहनों का काम", "pa": "बड्डी गड्डियां दा काम" },
      { "icon": "🏠", "en": "Doorstep Service", "hi": "घर पर सर्विस", "pa": "घरे पर सर्विस" },
      { "icon": "📜", "en": "Service History Record", "hi": "सर्विस रिकॉर्ड", "pa": "सर्विस दी कॉपी" },
      { "icon": "🛑", "en": "Brake Check", "hi": "ब्रेक की जांच", "pa": "ब्रेक दी परख" },
      { "icon": "🛢️", "en": "Transmission Fluid", "hi": "गियर ऑयल", "pa": "गियर दा तेल" },
      { "icon": "🧼", "en": "Degreasing", "hi": "चिकनाई की सफ़ाई", "pa": "तेल दी सफ़ाई" },
      { "icon": "🏗️", "en": "Chassis Work", "hi": "चेसिस का काम", "pa": "गाड़ी दी बॉडी दा काम" },
      { "icon": "📻", "en": "Stereo Fitting", "hi": "म्यूजिक सिस्टम", "pa": "गाणे बणाणे आली मशीन" },
      { "icon": "🔐", "en": "Central Locking", "hi": "सेंट्रल लॉकिंग", "pa": "तगड़ा लॉक" },
      { "icon": "🧼", "en": "Glass Cleaning", "hi": "कांच की सफ़ाई", "pa": "शीशे दी सफ़ाई" },
      { "icon": "🧪", "en": "Coolant Refill", "hi": "कूलेंट रिफिल", "pa": "कूलेंट दा पाणी" },
      { "icon": "🔩", "en": "Suspension Fix", "hi": "सस्पेंशन मरम्मत", "pa": "जंपरां दा काम" },
      { "icon": "📦", "en": "Ordered Rare Parts", "hi": "दुर्लभ सामान मंगवाना", "pa": "बखरा सामान मंगवाणा" },
      { "icon": "🧤", "en": "Clean Handover", "hi": "साफ़ गाड़ी वापिस", "pa": "सुथरी गाड़ी वापिस" },
      { "icon": "📋", "en": "Detailed Estimate", "hi": "विस्तृत अनुमान", "pa": "पूरा खर्चा दस्सा" },
      { "icon": "🧥", "en": "Seat Cover Fitting", "hi": "सीट कवर फिटिंग", "pa": "सीट कवर दा काम" },
      { "icon": "🚿", "en": "Foam Wash", "hi": "फोम वॉश", "pa": "झाग आली धुलाई" },
      { "icon": "🚗", "en": "Second Hand Expert", "hi": "पुरानी गाड़ी के जानकार", "pa": "पुराणी गड्डियां रे सयाणे" },
      { "icon": "🛞", "en": "Alloy Wheel Care", "hi": "एलॉय व्हील केयर", "pa": "महंगे टायरां दा ध्यान" },
      { "icon": "⛽", "en": "Quality Fuel", "hi": "शुद्ध तेल", "pa": "खरा तेल" },
      { "icon": "🧴", "en": "Anti-Rust Coating", "hi": "जंग रोधी कोटिंग", "pa": "जंग ते बचाओ" },
      { "icon": "🪑", "en": "Waiting Lounge", "hi": "बैठने की जगह", "pa": "बैठणे दी जगह" },
      { "icon": "☕", "en": "Coffee/Tea Station", "hi": "चाय-कॉफी", "pa": "चाह-पाणी" },
      { "icon": "💼", "en": "Corporate Fleet", "hi": "कॉर्पोरेट सर्विस", "pa": "दफ्तरे आली गड्डियां" },
      { "icon": "📑", "en": "Warranty Claim Support", "hi": "वारंटी सहायता", "pa": "वारंटी विच मदद" },
      { "icon": "🛠️", "en": "Modern Equipment", "hi": "नयी मशीनें", "pa": "नवी मशीनां" },
      { "icon": "🔍", "en": "Scanning Tool", "hi": "कंप्यूटर स्कैनिंग", "pa": "कंप्यूटरे सती जांच" },
      { "icon": "💡", "en": "Bulb Replacement", "hi": "बल्ब बदलना", "pa": "बल्ब बदली" },
      { "icon": "🛢️", "en": "Greasing", "hi": "ग्रीसिंग", "pa": "ग्रीसिंग" },
      { "icon": "🌟", "en": "Top Mechanic in HP", "hi": "इलाके का बेस्ट मैकेनिक", "pa": "इलाके दा सबन ते खरा मिस्त्री" },
      { "icon": "🏁", "en": "Ready for Road Trip", "hi": "सफर के लिए तैयार", "pa": "सफरे तांई तैयार" },
      { "icon": "🤝", "en": "Great Communication", "hi": "साफ़ बातचीत", "pa": "खरी गल्लां" }
    ],
    "fitness_and_wellness": [
      { "icon": "🏋️", "en": "Heavy Duty Equipment", "hi": "मज़बूत मशीनें", "pa": "तगड़ी मशीनां" },
      { "icon": "💪", "en": "Best Bodybuilding Gym", "hi": "बॉडीबिल्डिंग के लिए उत्तम", "pa": "शरीर बणाणे तांई खरा" },
      { "icon": "🧘", "en": "Peaceful Yoga Studio", "hi": "शांत योग स्थान", "pa": "शांति आली योगा जगह" },
      { "icon": "🤝", "en": "Motivating Trainer", "hi": "प्रेरक ट्रेनर", "pa": "जोश भरदे लोग" },
      { "icon": "🏃", "en": "Spacious Cardio Area", "hi": "खुला कार्डियो एरिया", "pa": "दौड़ने तांई खुली जगह" },
      { "icon": "🧼", "en": "Clean Locker Rooms", "hi": "साफ़ लॉकर रूम", "pa": "सुथरा लॉकर" },
      { "icon": "💦", "en": "Good Ventilation", "hi": "हवादार", "pa": "खुली हवा" },
      { "icon": "⚡", "en": "High Energy Music", "hi": "ऊर्जावान संगीत", "pa": "जोश भरदे गाणे" },
      { "icon": "🕒", "en": "24/7 Access", "hi": "हर समय खुला", "pa": "हर बखत खुला" },
      { "icon": "🥦", "en": "Diet Planning", "hi": "डाइट सलाह", "pa": "खाणे-पीणे री सलाह" },
      { "icon": "🥤", "en": "Fresh Juice Bar", "hi": "ताज़ा जूस", "pa": "ताजा जूस" },
      { "icon": "🥊", "en": "Boxing Ring", "hi": "बॉक्सिंग रिंग", "pa": "बॉक्सिंग दी जगह" },
      { "icon": "🤸", "en": "Zumba/Dance Class", "hi": "जुम्बा क्लासेस", "pa": "नाच-गाणे आली कसरत" },
      { "icon": "⚖️", "en": "Accurate Weighing", "hi": "सटीक वजन मशीन", "pa": "सई वजन मशीन" },
      { "icon": "🚿", "en": "Hot Shower", "hi": "गरम पानी स्नान", "pa": "ताते पाणि दा स्नान" },
      { "icon": "🧴", "en": "Supplements Available", "hi": "सप्लीमेंट उपलब्ध", "pa": "पाउडर-दवाई मिलदी" },
      { "icon": "🧺", "en": "Free Towels", "hi": "मुफ्त तौलिए", "pa": "फ्री साफ़े" },
      { "icon": "🧘", "en": "Meditation Corner", "hi": "ध्यान केंद्र", "pa": "शांति आला कोणा" },
      { "icon": "👟", "en": "Indoor Track", "hi": "अंदर दौड़ने का ट्रैक", "pa": "अंदरै दौड़णे दा रस्ता" },
      { "icon": "📅", "en": "Flexible Memberships", "hi": "आसान मेंबरशिप", "pa": "सजिलो मेंबरशिप" },
      { "icon": "💸", "en": "Value for Money", "hi": "पैसा वसूल", "pa": "पूरा पैसा वसूल" },
      { "icon": "🛡️", "en": "Safe for Women", "hi": "महिलाओं के लिए सुरक्षित", "pa": "जणाणियां तांई सुरक्षित" },
      { "icon": "🧒", "en": "Kids Fitness", "hi": "बच्चों की फिटनेस", "pa": "बालकां तांई कसरत" },
      { "icon": "🏊", "en": "Clean Pool", "hi": "साफ़ पूल", "pa": "सुथरा ताल" },
      { "icon": "🧖", "en": "Steam Room", "hi": "स्टीम रूम", "pa": "भाप आला कमरा" },
      { "icon": "🪜", "en": "Step Aerobics", "hi": "एरोबिक्स", "pa": "एरोबिक्स" },
      { "icon": "🍎", "en": "Nutritionist Onsite", "hi": "पोषण विशेषज्ञ", "pa": "खाणे-पीणे रे सयाणे" },
      { "icon": "📞", "en": "Punctual Classes", "hi": "समय पर क्लासेस", "pa": "बखत पर क्लास" },
      { "icon": "🩹", "en": "First Aid Kit", "hi": "प्राथमिक चिकित्सा", "pa": "दवाई-पट्टी दा डब्बा" },
      { "icon": "🚴", "en": "Spinning Studio", "hi": "साइकिलिंग क्लास", "pa": "साइकिल कसरत" },
      { "icon": "📱", "en": "App Based Tracking", "hi": "ऐप से ट्रैकिंग", "pa": "फोने पर हिसाब" },
      { "icon": "🪑", "en": "Rest Area", "hi": "आराम की जगह", "pa": "आराम दी जगह" },
      { "icon": "🅿️", "en": "Parking Space", "hi": "पार्किंग", "pa": "गाड़ी तांई जगह" },
      { "icon": "📶", "en": "Free Wi-Fi", "hi": "वाई-फ़ाई", "pa": "फ्री इंटरनेट" },
      { "icon": "🥤", "en": "Water Dispenser", "hi": "पानी की सुविधा", "pa": "पीणे दा पाणी" },
      { "icon": "🔋", "en": "Phone Charging", "hi": "चार्जिंग पॉइंट", "pa": "चार्जिंग पॉइंट" },
      { "icon": "👕", "en": "Merchandise Shop", "hi": "फिटनेस स्टोर", "pa": "कसरते दा सामान" },
      { "icon": "🔥", "en": "Fat Burn Focus", "hi": "वजन घटाने पर ध्यान", "pa": "वजन घटाणे पर जोर" },
      { "icon": "💪", "en": "Strength Training", "hi": "ताकत की ट्रेनिंग", "pa": "ताकत बणाणे दा काम" },
      { "icon": "🤸‍♂️", "en": "Personal Training", "hi": "निजी ट्रेनर", "pa": "खास ट्रेनर" },
      { "icon": "🌈", "en": "Inclusive Space", "hi": "सबके लिए", "pa": "सबन तांई" },
      { "icon": "📜", "en": "Certified Coaches", "hi": "प्रमाणित कोच", "pa": "डिग्री आले उस्ताद" },
      { "icon": "🏙️", "en": "Great Location", "hi": "अच्छी जगह", "pa": "खरी जगह" },
      { "icon": "🌳", "en": "Outdoor Sessions", "hi": "बाहर की क्लासेस", "pa": "बाहरे कसरत" },
      { "icon": "🔇", "en": "Quiet Meditation", "hi": "शांतिपूर्ण ध्यान", "pa": "शांति आला ध्यान" },
      { "icon": "🧴", "en": "Skin Care After Workout", "hi": "त्वचा की देखभाल", "pa": "चमड़ी दा ध्यान" },
      { "icon": "🧘‍♀️", "en": "Pregnancy Yoga", "hi": "गर्भावस्था योग", "pa": "भारी जणाणियां तांई योगा" },
      { "icon": "🧬", "en": "Body Composition Analysis", "hi": "बॉडी चेकअप", "pa": "शरीरे दी जांच" },
      { "icon": "🩺", "en": "Heart Rate Monitoring", "hi": "हृदय गति जांच", "pa": "दिल्ले दी धड़कन जांच" },
      { "icon": "🔋", "en": "Boosted Stamina", "hi": "स्टैमिना बढ़ाना", "pa": "ताकत बढ़ाणा" },
      { "icon": "💎", "en": "Premium Gym Vibe", "hi": "शानदार जिम", "pa": "बड्डा सुणा जिम" },
      { "icon": "🧥", "en": "Winter Workout Ready", "hi": "सर्दियों के लिए तैयार", "pa": "पाले तांई तैयार" },
      { "icon": "🤝", "en": "Community Spirit", "hi": "भाईचारा", "pa": "भाईचारा" },
      { "icon": "🚶", "en": "Easy Walking Access", "hi": "पैदल पहुँच", "pa": "नेड़े ही है" },
      { "icon": "🧊", "en": "Ice Bath Facility", "hi": "आइस बाथ", "pa": "ठंडे पाणि दा स्नान" },
      { "icon": "👟", "en": "Good Shoe Storage", "hi": "जूते रखने की जगह", "pa": "जूते रखणे दी जगह" },
      { "icon": "💡", "en": "Good Lighting", "hi": "शानदार रोशनी", "pa": "खरी रौशनी" },
      { "icon": "🌟", "en": "Highly Rated", "hi": "सबसे बढ़िया", "pa": "सबन ते खरा" },
      { "icon": "💪", "en": "Body Transformation", "hi": "बदलाव", "pa": "शरीरे विच बदलाव" },
      { "icon": "🏆", "en": "Top Wellness Center", "hi": "बेस्ट हेल्थ सेंटर", "pa": "सबन ते खरा सेंटर" }
    ],
    "education": [
      { "icon": "📚", "en": "Quality Teaching", "hi": "अच्छी पढ़ाई", "pa": "खरी पढ़ाई" },
      { "icon": "🎓", "en": "Successful Results", "hi": "सफल परिणाम", "pa": "पास होणे दी गारंटी" },
      { "icon": "👨‍🏫", "en": "Experienced Teachers", "hi": "अनुभवी शिक्षक", "pa": "सयाणे उस्ताद" },
      { "icon": "💻", "en": "Modern Computer Lab", "hi": "आधुनिक लैब", "pa": "नवी कंप्यूटर लैब" },
      { "icon": "🏫", "en": "Safe Campus", "hi": "सुरक्षित कैंपस", "pa": "सुरक्षित जगह" },
      { "icon": "📖", "en": "Rich Library", "hi": "बड़ी लाइब्रेरी", "pa": "किताबों दा भण्डार" },
      { "icon": "🧒", "en": "Friendly for Kids", "hi": "बच्चों के अनुकूल", "pa": "बालकां तांई खरा" },
      { "icon": "📋", "en": "Clear Syllabus", "hi": "साफ़ सिलेबस", "pa": "पढ़ाई दी खरी जानकारी" },
      { "icon": "🚌", "en": "Reliable Bus Service", "hi": "बस की सुविधा", "pa": "बसे दा इंतज़ाम" },
      { "icon": "🔬", "en": "Well-Equipped Science Lab", "hi": "साइंस लैब", "pa": "साइंस दी लैब" },
      { "icon": "🎨", "en": "Creative Arts", "hi": "कला और क्राफ्ट", "pa": "कला-कारी दा काम" },
      { "icon": "⚽", "en": "Sports Facility", "hi": "खेल की सुविधा", "pa": "खेळां दी सुविधा" },
      { "icon": "💸", "en": "Reasonable Fees", "hi": "उचित फीस", "pa": "सई फीस" },
      { "icon": "🤝", "en": "Career Guidance", "hi": "करियर सलाह", "pa": "नौकरी दी सलाह" },
      { "icon": "📜", "en": "Recognized Degree", "hi": "मान्यता प्राप्त", "pa": "डिग्री दी मान्यता" },
      { "icon": "🗣️", "en": "English Speaking Environment", "hi": "अंग्रेजी वातावरण", "pa": "अंग्रेजी बोलणे दा जोर" },
      { "icon": "🛡️", "en": "Strict Discipline", "hi": "अनुशासन", "pa": "कायदे-कानून" },
      { "icon": "🕒", "en": "Flexible Timing", "hi": "आसान समय", "pa": "सई बखत" },
      { "icon": "🥣", "en": "Hygienic Canteen", "hi": "साफ़ कैंटीन", "pa": "सुथरी कैंटीन" },
      { "icon": "🥤", "en": "Drinking Water", "hi": "पीने का पानी", "pa": "पीणे दा पाणी" },
      { "icon": "🪑", "en": "Comfortable Benches", "hi": "बैठने की सुविधा", "pa": "बैठणे दी खरी जगह" },
      { "icon": "🚿", "en": "Clean Toilets", "hi": "साफ़ शौचालय", "pa": "सुथरे टॉयलेट" },
      { "icon": "📱", "en": "Online Class Support", "hi": "ऑनलाइन क्लासेस", "pa": "फोने पर पढ़ाई" },
      { "icon": "🧥", "en": "Smart Uniform", "hi": "सुंदर वर्दी", "pa": "सुणी वर्दी" },
      { "icon": "🌍", "en": "Overall Development", "hi": "सर्वांगीण विकास", "pa": "पूरा विकास" },
      { "icon": "💡", "en": "Motivational Sessions", "hi": "प्रेरक सत्र", "pa": "जोश भरदी गल्लां" },
      { "icon": "📝", "en": "Regular Tests", "hi": "नियमित पेपर", "pa": "रोजां रे पेपर" },
      { "icon": "📈", "en": "Student Progress Tracking", "hi": "प्रगति की जांच", "pa": "पढ़ाई दी परख" },
      { "icon": "👩‍💻", "en": "Coding Lessons", "hi": "कोडिंग की पढ़ाई", "pa": "कंप्यूटर कोडिंग" },
      { "icon": "🧩", "en": "Problem Solving Focus", "hi": "सवाल हल करना", "pa": "मुश्किल हल करणी" },
      { "icon": "🌲", "en": "Green Campus", "hi": "हरा-भरा परिसर", "pa": "हरियाली आली जगह" },
      { "icon": "📞", "en": "Good Parent-Teacher Link", "hi": "अभिभावक-शिक्षक तालमेल", "pa": "घरवाले ते उस्ताद" },
      { "icon": "🎤", "en": "Confidence Building", "hi": "आत्मविश्वास", "pa": "हिम्मत बढ़ाणा" },
      { "icon": "🗺️", "en": "Field Trips", "hi": "शैक्षिक भ्रमण", "pa": "पढ़ाई तांई सैर" },
      { "icon": "🧘", "en": "Meditation for Students", "hi": "छात्रों का ध्यान", "pa": "पढ़ने आलें दा ध्यान" },
      { "icon": "📅", "en": "Timely Exams", "hi": "समय पर परीक्षा", "pa": "बखत पर पेपर" },
      { "icon": "💎", "en": "Best Value Education", "hi": "बेहतरीन शिक्षा", "pa": "सबन ते खरी पढ़ाई" },
      { "icon": "🧤", "en": "Safety Drills", "hi": "सुरक्षा अभ्यास", "pa": "बचाओ दी तैयारी" },
      { "icon": "🔋", "en": "Encouraging Atmosphere", "hi": "उत्साहजनक माहौल", "pa": "जोश आला माहौल" },
      { "icon": "🤝", "en": "Supportive Seniors", "hi": "मददगार छात्र", "pa": "मददगार संगी" },
      { "icon": "🏘️", "en": "Community Service", "hi": "समाज सेवा", "pa": "ग्रां दी सेवा" },
      { "icon": "🎶", "en": "Music & Culture", "hi": "संगीत और संस्कृति", "pa": "नाच-गाणा ते संस्कृति" },
      { "icon": "🧺", "en": "Clean Playground", "hi": "साफ़ खेल का मैदान", "pa": "सुथरा मैदान" },
      { "icon": "🛡️", "en": "CCTV Security", "hi": "कैमरा सुरक्षा", "pa": "कैमरे री सुरक्षा" },
      { "icon": "👔", "en": "Job Placement", "hi": "नौकरी की सुविधा", "pa": "नौकरी दा इंतज़ाम" },
      { "icon": "💼", "en": "Interview Prep", "hi": "इंटरव्यू की तैयारी", "pa": "इंटरव्यू दी तैयारी" },
      { "icon": "🗣️", "en": "Debate Classes", "hi": "डिबेट क्लास", "pa": "गल्लां-बातां दी क्लास" },
      { "icon": "🎒", "en": "Low Stress Learning", "hi": "बिना तनाव की पढ़ाई", "pa": "बिना टेंशन दी पढ़ाई" },
      { "icon": "🏡", "en": "Hostel Facility", "hi": "होस्टल की सुविधा", "pa": "रैहणे दा इंतज़ाम" },
      { "icon": "🧊", "en": "Cool Environment", "hi": "ठंडा माहौल", "pa": "ठंडा माहौल" },
      { "icon": "🔥", "en": "Winter Heater Access", "hi": "सर्दियों में हीटर", "pa": "पाले विच हीटर" },
      { "icon": "🧗", "en": "Adventure Education", "hi": "रोमांचक शिक्षा", "pa": "मौज-मस्ती आली पढ़ाई" },
      { "icon": "🌟", "en": "Inspiring Leaders", "hi": "प्रेरक नेतृत्व", "pa": "बड्डे लोग" },
      { "icon": "📜", "en": "Merit Scholarships", "hi": "छात्रवृत्ति", "pa": "पढ़ाई तांई पैसे" },
      { "icon": "🔌", "en": "Power Backup", "hi": "बिजली बैकअप", "pa": "बिजली दा पूरा काम" },
      { "icon": "👔", "en": "Professional Ethics", "hi": "व्यावसायिक नैतिकता", "pa": "तरीके आली पढ़ाई" },
      { "icon": "📦", "en": "Free Books/Study Material", "hi": "मुफ्त किताबें", "pa": "फ्री किताबें" },
      { "icon": "🏆", "en": "Top Ranked School", "hi": "बेस्ट स्कूल", "pa": "सबन ते खरा स्कूल" },
      { "icon": "🏠", "en": "Feels Like Home", "hi": "घर जैसा", "pa": "घरे जिया" },
      { "icon": "✨", "en": "Bright Future", "hi": "उज्ज्वल भविष्य", "pa": "सुणा भविष्य" }
    ],
    "home_services": [
      { "icon": "💡", "en": "Expert Electrician", "hi": "कुशल इलेक्ट्रीशियन", "pa": "बिजली दा सयाणो मिस्त्री" },
      { "icon": "🚰", "en": "Reliable Plumber", "hi": "भरोसेमंद प्लंबर", "pa": "विस्वासिलो प्लंबर" },
      { "icon": "🔨", "en": "Skillful Carpenter", "hi": "कुशल बढ़ई", "pa": "काठ दा सयाणो मिस्त्री" },
      { "icon": "🎨", "en": "Neat Painter", "hi": "सफ़ाई से पेंट करने वाला", "pa": "सफ़ाई आला रंग-पेंट" },
      { "icon": "🏠", "en": "Quality Construction", "hi": "मज़बूत निर्माण", "pa": "तगड़ा लेंटर ते कोठी" },
      { "icon": "⚡", "en": "Fast Emergency Repair", "hi": "तुरंत मरम्मत", "pa": "झटपट रिपेयर" },
      { "icon": "💵", "en": "No Hidden Costs", "hi": "कोई अतिरिक्त खर्चा नहीं", "pa": "कोई फालतू खर्चा नी" },
      { "icon": "🤝", "en": "Polite Behavior", "hi": "विनम्र व्यवहार", "pa": "मिठु बोलणा" },
      { "icon": "⏰", "en": "Always Punctual", "hi": "समय का पाबंद", "pa": "बखत दा पाबंद" },
      { "icon": "🧹", "en": "Post-Work Cleaning", "hi": "काम के बाद सफ़ाई", "pa": "कामे बाद दी सफ़ाई" },
      { "icon": "🛠️", "en": "Modern Tools Used", "hi": "आधुनिक औज़ार", "pa": "नवी मशीनां" },
      { "icon": "🛡️", "en": "Safe & Trustworthy", "hi": "सुरक्षित और भरोसेमंद", "pa": "विस्वासिलो बंदा" },
      { "icon": "🪟", "en": "Window & Door Expert", "hi": "खिड़की-दरवाजे के जानकार", "pa": "खिडकियां-दरवाजे दा सयाणो" },
      { "icon": "🔌", "en": "Safe Wiring", "hi": "सुरक्षित वायरिंग", "pa": "खरा बिजली दा काम" },
      { "icon": "🚰", "en": "Leakage Fixed", "hi": "लीकेज ठीक की", "pa": "पाणी टपकणा बंद" },
      { "icon": "🏗️", "en": "Strong Foundation", "hi": "मज़बूत नींव", "pa": "मजबूत नींव" },
      { "icon": "🚪", "en": "Lock Repair Expert", "hi": "ताला मरम्मत", "pa": "ताले दा सयाणो" },
      { "icon": "🧱", "en": "Beautiful Masonry", "hi": "सुंदर चिनाई", "pa": "सुणी चिनाई" },
      { "icon": "🚽", "en": "Sanitary Fitting", "hi": "सैनिटरी फिटिंग", "pa": "बाथरूम दा काम" },
      { "icon": "🧺", "en": "Tile Flooring", "hi": "टाइल वर्क", "pa": "टाइल दा काम" },
      { "icon": "🛋️", "en": "Furniture Polish", "hi": "फर्नीचर पॉलिश", "pa": "फर्नीचर दी पॉलिश" },
      { "icon": "🪚", "en": "Precision Cutting", "hi": "सटीक कटाई", "pa": "सई कटाई" },
      { "icon": "🌡️", "en": "Geyser Repair", "hi": "गीज़र मरम्मत", "pa": "गीज़र रिपेयर" },
      { "icon": "💧", "en": "Tank Cleaning", "hi": "टंकी की सफ़ाई", "pa": "पाणि दी टंकी" },
      { "icon": "📞", "en": "Easy to Contact", "hi": "संपर्क में आसान", "pa": "सजिलो बुलाबा" },
      { "icon": "🧤", "en": "Safety Protocols", "hi": "सुरक्षा नियम", "pa": "बचाओ रे नियम" },
      { "icon": "📦", "en": "Genuine Materials", "hi": "असली सामान", "pa": "खरा सामान" },
      { "icon": "💎", "en": "Luxury Finish", "hi": "शानदार फिनिश", "pa": "बड्डा सुणा काम" },
      { "icon": "💸", "en": "Reasonable Labor", "hi": "सही मज़दूरी", "pa": "सई दिहाड़ी" },
      { "icon": "🤝", "en": "Honest Advice", "hi": "सही सलाह", "pa": "खरी सलाह" },
      { "icon": "🔨", "en": "Iron Welding", "hi": "वेल्डिंग का काम", "pa": "लोहे दी वेल्डिंग" },
      { "icon": "🧥", "en": "Waterproofing", "hi": "वॉटरप्रूफिंग", "pa": "सीलन ते बचाओ" },
      { "icon": "🏚️", "en": "Renovation Specialist", "hi": "मरम्मत विशेषज्ञ", "pa": "पुराणा घर चमकाणा" },
      { "icon": "🪜", "en": "High Ceiling Access", "hi": "ऊंचाई का काम", "pa": "उंचाई दा काम" },
      { "icon": "🔌", "en": "Inverter Setup", "hi": "इनवर्टर सेटअप", "pa": "इनवर्टर दा काम" },
      { "icon": "💡", "en": "Lighting Design", "hi": "लाइटिंग सजावट", "pa": "बत्तियां दी सजावट" },
      { "icon": "🧱", "en": "Brick Work", "hi": "ईंटों का काम", "pa": "इंटां दा काम" },
      { "icon": "🪵", "en": "Hardwood Floors", "hi": "लकड़ी का फर्श", "pa": "लकड़ी दा फर्श" },
      { "icon": "🪟", "en": "Glass Fitting", "hi": "कांच का काम", "pa": "शीशे दा काम" },
      { "icon": "🏡", "en": "Garden Maintenance", "hi": "बगीचे की देखरेख", "pa": "बगीचे दा ध्यान" },
      { "icon": "🧹", "en": "Deep Cleaning", "hi": "गहरी सफ़ाई", "pa": "पूरी सफ़ाई" },
      { "icon": "🐜", "en": "Pest Control", "hi": "कीड़े-मकौड़े नियंत्रण", "pa": "कीड़े मारणा" },
      { "icon": "🛋️", "en": "Sofa Cleaning", "hi": "सोफा सफ़ाई", "pa": "सोफे दी सफ़ाई" },
      { "icon": "🔌", "en": "Appliance Repair", "hi": "उपकरण मरम्मत", "pa": "मशीनां दी रिपेयर" },
      { "icon": "🧼", "en": "Water Tank Clean", "hi": "पानी की टंकी साफ़", "pa": "टंकी दी सफ़ाई" },
      { "icon": "🚪", "en": "Aluminum Work", "hi": "एल्युमिनियम का काम", "pa": "एल्युमिनियम दा काम" },
      { "icon": "🔥", "en": "Chimney Repair", "hi": "चिमनी मरम्मत", "pa": "चिमनी दी रिपेयर" },
      { "icon": "🏠", "en": "New House Map", "hi": "मकान का नक्शा", "pa": "कोठी दा नक्शा" },
      { "icon": "🔩", "en": "Grill Installation", "hi": "ग्रिल लगवाना", "pa": "ग्रिल दा काम" },
      { "icon": "🔌", "en": "Solar Installation", "hi": "सोलर पैनल", "pa": "धूप आली बिजली" },
      { "icon": "👔", "en": "Highly Professional", "hi": "बहुत पेशेवर", "pa": "बड्डा सयाणो बंदा" },
      { "icon": "📜", "en": "Warranty on Work", "hi": "काम की वारंटी", "pa": "कामे दी वारंटी" },
      { "icon": "📋", "en": "Free Quotation", "hi": "मुफ्त अनुमान", "pa": "फ्री खर्चा दस्सा" },
      { "icon": "🛠️", "en": "Equipped with Tools", "hi": "औज़ारों से लैस", "pa": "पूरा सामान" },
      { "icon": "🌟", "en": "Top Rated in Town", "hi": "इलाके का बेस्ट", "pa": "सबन ते खरा मिस्त्री" },
      { "icon": "🚚", "en": "Moving Help", "hi": "सामान शिफ्ट करना", "pa": "सामान बदली करणा" },
      { "icon": "🤝", "en": "Friendly Team", "hi": "दोस्ताना टीम", "pa": "मिठु लोग" },
      { "icon": "⏰", "en": "Quick Response", "hi": "तुरंत सुणवाई", "pa": "झटपट मदद" },
      { "icon": "💎", "en": "Excellent Quality", "hi": "शानदार क्वालिटी", "pa": "बड्डा खरा काम" },
      { "icon": "🏠", "en": "Dream Home Helper", "hi": "सपनों का घर", "pa": "सुणी कोठी" }
    ],
    "professional_services": [
      { "icon": "⚖️", "en": "Expert Lawyer", "hi": "अनुभवी वकील", "pa": "सयाणो वकील" },
      { "icon": "📊", "en": "Best CA/Accounting", "hi": "शानदार अकाउंटिंग", "pa": "हिसाबे दा सयाणो" },
      { "icon": "🤝", "en": "Trusted Consultant", "hi": "भरोसेमंद सलाहकार", "pa": "विस्वासिलो सलाहकार" },
      { "icon": "🏠", "en": "Great Real Estate Agent", "hi": "अच्छे प्रॉपर्टी डीलर", "pa": "जमीने दा खरा डीलर" },
      { "icon": "🛡️", "en": "Reliable Insurance", "hi": "भरोसेमंद बीमा", "pa": "विस्वासिलो बीमा" },
      { "icon": "📑", "en": "Easy Documentation", "hi": "आसान काग़ज़ी काम", "pa": "सजिलो काग़ज़ात दा काम" },
      { "icon": "🗣️", "en": "Clear Communication", "hi": "साफ़ बातचीत", "pa": "खरी गल्लां" },
      { "icon": "⏰", "en": "On Time Delivery", "hi": "समय पर काम", "pa": "बखत पर काम" },
      { "icon": "💡", "en": "Great Business Ideas", "hi": "अच्छी बिज़नेस सलाह", "pa": "काम बणाणे दी सलाह" },
      { "icon": "📜", "en": "Legal Compliance", "hi": "कानूनी साक्षरता", "pa": "कानूने दा सयाणो" },
      { "icon": "💰", "en": "Saved Money", "hi": "पैसे की बचत", "pa": "पैसे दी बचत" },
      { "icon": "🔐", "en": "Confidentiality", "hi": "गोपनीयता", "pa": "गुपचुप काम" },
      { "icon": "💻", "en": "Digital Support", "hi": "डिजिटल सहायता", "pa": "कम्प्यूटरे दी मदद" },
      { "icon": "📞", "en": "Quick Follow-up", "hi": "तुरंत संपर्क", "pa": "झटपट सुणवाई" },
      { "icon": "🌍", "en": "Wide Network", "hi": "बड़ा नेटवर्क", "pa": "बड्डी जान-पहचाण" },
      { "icon": "💎", "en": "Premium Advice", "hi": "शानदार सलाह", "pa": "खरी सलाह" },
      { "icon": "💸", "en": "Reasonable Service Fee", "hi": "सही फीस", "pa": "सई फीस" },
      { "icon": "👔", "en": "Highly Professional", "hi": "बहुत पेशेवर", "pa": "तरीके आला काम" },
      { "icon": "📈", "en": "Growth Focused", "hi": "तरक्की पर ध्यान", "pa": "तरक्की तांई जोर" },
      { "icon": "🛡️", "en": "Risk Management", "hi": "जोखिम प्रबंधन", "pa": "खतरे ते बचाओ" },
      { "icon": "📜", "en": "No Paperwork Hassle", "hi": "काग़ज़ों की कोई टेंशन नहीं", "pa": "काग़ज़ात दी कोई टेंशन नी" },
      { "icon": "🗺️", "en": "Local Area Knowledge", "hi": "स्थानीय जानकारी", "pa": "इथै री पूरी खबर" },
      { "icon": "🤝", "en": "Patient Listening", "hi": "ध्यान से सुनते हैं", "pa": "धीरज सती सुणदे" },
      { "icon": "⚖️", "en": "Court Representation", "hi": "अदालत में सहायता", "pa": "अदालते विच मदद" },
      { "icon": "🏛️", "en": "Government Liaison", "hi": "सरकारी काम", "pa": "सरकारी काम" },
      { "icon": "📈", "en": "Tax Planning", "hi": "टैक्स प्लानिंग", "pa": "टैक्स दा हिसाब" },
      { "icon": "🏘️", "en": "Property Valuation", "hi": "प्रॉपर्टी की सही कीमत", "pa": "जमीने दा सई मोल" },
      { "icon": "📜", "en": "Affidavit Expert", "hi": "शपथ पत्र विशेषज्ञ", "pa": "काग़ज़ात बणाणे दा सयाणो" },
      { "icon": "🖋️", "en": "Fast Agreement", "hi": "जल्दी एग्रीमेंट", "pa": "झटपट एग्रीमेंट" },
      { "icon": "🏢", "en": "Office Visit Comfort", "hi": "आरामदायक दफ्तर", "pa": "दफ्तरे विच सुकूण" },
      { "icon": "📦", "en": "Logistics Help", "hi": "लॉजिस्टिक सहायता", "pa": "सामान भेजणे दी मदद" },
      { "icon": "🛡️", "en": "Family Protection", "hi": "परिवार की सुरक्षा", "pa": "टब्बरे दी सुरक्षा" },
      { "icon": "⚖️", "en": "Dispute Resolution", "hi": "विवाद का निपटारा", "pa": "झगड़ा खत्म" },
      { "icon": "💸", "en": "Low Retainer", "hi": "सस्ती फीस", "pa": "घट फीस" },
      { "icon": "📞", "en": "24/7 Helpline", "hi": "हेल्पलाइन सुविधा", "pa": "हर बखत मदद" },
      { "icon": "💼", "en": "Corporate Service", "hi": "कॉर्पोरेट सेवा", "pa": "दफ्तरे आला काम" },
      { "icon": "🌟", "en": "Top Consultant", "hi": "बेस्ट कंसल्टेंट", "pa": "सबन ते खरा सयाणो" },
      { "icon": "🛡️", "en": "Privacy Protected", "hi": "गोपनीयता सुरक्षित", "pa": "गल्लां लुक्की दी" },
      { "icon": "🤝", "en": "Life Time Support", "hi": "हमेशा के लिए सहायता", "pa": "उमरे भर दी मदद" },
      { "icon": "🌍", "en": "Global Standards", "hi": "विश्व स्तरीय", "pa": "दुनिया भर दा ज्ञान" },
      { "icon": "👔", "en": "Sharp & Efficient", "hi": "तेज़ और कुशल", "pa": "तेज़ ते सयाणो" },
      { "icon": "📋", "en": "Detailed Audit", "hi": "पूरी जांच", "pa": "पूरा हिसाब-किताब" },
      { "icon": "📈", "en": "Financial Stability", "hi": "आर्थिक मजबूती", "pa": "पैसे दी मजबूती" },
      { "icon": "💎", "en": "Exclusivity", "hi": "खास सेवा", "pa": "खास सेवा" },
      { "icon": "💡", "en": "Innovative Solutions", "hi": "नये उपाय", "pa": "नवे तरीके" },
      { "icon": "⚖️", "en": "Consumer Rights", "hi": "उपभोक्ता अधिकार", "pa": "ग्राहकां दे हक" },
      { "icon": "📜", "en": "Patent Expert", "hi": "पेटेंट विशेषज्ञ", "pa": "पेटेंट दा सयाणो" },
      { "icon": "🏠", "en": "Home Loan Support", "hi": "होम लोन सहायता", "pa": "कोठी तांई लोन" },
      { "icon": "💼", "en": "Business License", "hi": "व्यापार लाइसेंस", "pa": "कामे दा लाइसेंस" },
      { "icon": "📱", "en": "WhatsApp Updates", "hi": "व्हाट्सएप पर जानकारी", "pa": "व्हाट्सएप पर खबर" },
      { "icon": "🤝", "en": "Ethical Values", "hi": "नैतिकता", "pa": "सई रस्ता" },
      { "icon": "⏰", "en": "Urgent Service OK", "hi": "अर्जेंट काम", "pa": "झटपट काम" },
      { "icon": "📊", "en": "GST Expert", "hi": "GST विशेषज्ञ", "pa": "GST दा सयाणो" },
      { "icon": "🏢", "en": "Main Market Office", "hi": "बाज़ार में दफ्तर", "pa": "बाज़ारे विच दफ्तर" },
      { "icon": "🅿️", "en": "Ample Client Parking", "hi": "पार्किंग सुविधा", "pa": "गाड़ी तांई जगह" },
      { "icon": "🧤", "en": "Error Free Work", "hi": "गलती रहित काम", "pa": "बिना गलती दा काम" },
      { "icon": "🌟", "en": "Highly Recommended", "hi": "ज़रूर संपर्क करें", "pa": "जरूर मिलणा" },
      { "icon": "🤝", "en": "Friendly Secretary", "hi": "मिलनसार स्टाफ", "pa": "मिठु स्टाफ" },
      { "icon": "💎", "en": "Priceless Advice", "hi": "कीमती सलाह", "pa": "बड्डी खरी सलाह" },
      { "icon": "🏆", "en": "Number 1 Firm", "hi": "नंबर 1 फर्म", "pa": "सबन ते खरी कंपनी" }
    ]
  }
]

async function main() {
  console.log('Seeding massive multi-language tag library...');
  let count = 0;
  
  const categoryMap = {
    "food_and_dining": "Restaurant",
    "hotels_and_stay": "Hotel",
    "travel_and_tourism": "Travel",
    "local_shops": "Retail",
    "healthcare": "Medical",
    "personal_care": "Salon & Spa",
    "automotive": "Automotive",
    "fitness_and_wellness": "Gym",
    "education": "Education",
    "home_services": "Home Services",
    "professional_services": "Professional"
  };

  const tagData = predefinedTags[0];
  
  for (const [rawCategory, tags] of Object.entries(tagData)) {
    const category = categoryMap[rawCategory] || rawCategory.split('_').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ');
    
    for (const t of tags) {
      // 1. English
      if (t.en) {
        try {
          await prisma.industryTag.upsert({
            where: { category_tag_language: { category, tag: t.en, language: "English" } },
            update: { icon: t.icon },
            create: { category, tag: t.en, icon: t.icon, language: "English" }
          });
          count++;
        } catch(e) { console.error(e); }
      }
      
      // 2. Hindi
      if (t.hi) {
        try {
          await prisma.industryTag.upsert({
            where: { category_tag_language: { category, tag: t.hi, language: "Hindi" } },
            update: { icon: t.icon },
            create: { category, tag: t.hi, icon: t.icon, language: "Hindi" }
          });
          count++;
        } catch(e) { console.error(e); }
      }
      
      // 3. Pahadi
      if (t.pa) {
        try {
          await prisma.industryTag.upsert({
            where: { category_tag_language: { category, tag: t.pa, language: "Pahadi" } },
            update: { icon: t.icon },
            create: { category, tag: t.pa, icon: t.icon, language: "Pahadi" }
          });
          count++;
        } catch(e) { console.error(e); }
      }
    }
  }
  
  console.log(`Seeding complete. Inserted/Updated ${count} tags across multiple languages.`);
}

main()
  .catch(e => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
